/*
Navicat MySQL Data Transfer

Source Server         : jwzh
Source Server Version : 50538
Source Host           : localhost:3306
Source Database       : source_sqjw

Target Server Type    : MYSQL
Target Server Version : 50538
File Encoding         : 65001

Date: 2017-03-29 19:02:25
*/

SET FOREIGN_KEY_CHECKS=0;
DROP database IF EXISTS `source_sqjw`;
create database `source_sqjw`;
use `source_sqjw`;
-- ----------------------------
-- Table structure for code_hyzk
-- ----------------------------
DROP TABLE IF EXISTS `code_hyzk`;
CREATE TABLE `code_hyzk` (
  `code` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `hck_gxsj` datetime DEFAULT NULL,
  `hck_rksj` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for code_hzgx
-- ----------------------------
DROP TABLE IF EXISTS `code_hzgx`;
CREATE TABLE `code_hzgx` (
  `code` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `hck_gxsj` datetime DEFAULT NULL,
  `hck_rksj` datetime DEFAULT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_sqjw_czxx
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_sqjw_czxx`;
CREATE TABLE `t_bz_sqjw_czxx` (
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '更新时间',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '入库时间',
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `CREATDEPARTMENT` varchar(30) DEFAULT NULL COMMENT '创建单位',
  `CREATEDTIME` date DEFAULT NULL COMMENT '创建时间',
  `CREATOR` varchar(120) DEFAULT NULL COMMENT '创建人',
  `CZQK` varchar(400) DEFAULT NULL COMMENT '承租情况kind=czqk',
  `CZQK_ZW` varchar(255) DEFAULT NULL,
  `CZQK_GABZ` varchar(50) DEFAULT NULL COMMENT '承租情况kind=czqk_公安标准',
  `CZRCSRQ` date DEFAULT NULL COMMENT '承租人出生日期',
  `CZRFWCS` varchar(400) DEFAULT NULL COMMENT '承租人服务处所',
  `CZRLXDH` varchar(40) DEFAULT NULL COMMENT '承租人联系电话',
  `CZRMZ` varchar(30) DEFAULT NULL COMMENT '承租人民族kind=05',
  `CZRMZ_ZW` varchar(255) DEFAULT NULL,
  `CZRMZ_GABZ` varchar(50) DEFAULT NULL COMMENT '承租人民族kind=05_公安标准',
  `CZRXB` varchar(20) DEFAULT NULL COMMENT '承租人性别kind=01',
  `CZRXB_ZW` varchar(255) DEFAULT NULL,
  `CZRXB_GABZ` varchar(50) DEFAULT NULL COMMENT '承租人性别kind=01_公安标准',
  `CZRXM` varchar(60) DEFAULT NULL COMMENT '承租人姓名',
  `CZRYFZGX` varchar(30) DEFAULT NULL COMMENT '承租人与房主关系kind=gzdx_gxrlx',
  `CZRYFZGX_ZW` varchar(255) DEFAULT NULL,
  `CZRYFZGX_GABZ` varchar(50) DEFAULT NULL COMMENT '承租人与房主关系kind=gzdx_gxrlx_公安标准',
  `CZRYTGRGX` varchar(30) DEFAULT NULL COMMENT '承租人与托管人关系kind=gzdx_gxrlx',
  `CZRYTGRGX_ZW` varchar(255) DEFAULT NULL,
  `CZRYTGRGX_GABZ` varchar(50) DEFAULT NULL COMMENT '承租人与托管人关系kind=gzdx_gxrlx_公安标准',
  `CZRYWM` varchar(30) DEFAULT NULL COMMENT '承租人英文名',
  `CZRYWX` varchar(30) DEFAULT NULL COMMENT '承租人英文姓',
  `CZRZJHM` varchar(30) DEFAULT NULL COMMENT '承租人证件号码',
  `CZRZJZL` varchar(20) DEFAULT NULL COMMENT '承租人证件种类kind=wg_03',
  `CZRZJZL_ZW` varchar(255) DEFAULT NULL,
  `CZRZJZL_GABZ` varchar(50) DEFAULT NULL COMMENT '承租人证件种类kind=wg_03_公安标准',
  `CZRZY` varchar(100) DEFAULT NULL COMMENT '承租人职业kind=sqjw_czrk_zylb',
  `CZRZY_ZW` varchar(255) DEFAULT NULL,
  `CZRZY_GABZ` varchar(50) DEFAULT NULL COMMENT '承租人职业kind=sqjw_czrk_zylb_公安标准',
  `DELETEFLAG` varchar(4) DEFAULT NULL COMMENT '删除标志',
  `DOWNLOADFLAG` varchar(4) DEFAULT NULL COMMENT '下传标志',
  `FWXXID` varchar(100) DEFAULT NULL COMMENT '房屋信息id',
  `HCK_GXSJ` datetime DEFAULT NULL COMMENT '缓冲库更新时间',
  `HCK_RKSJ` datetime DEFAULT NULL COMMENT '缓冲库入库时间',
  `LASTUPDATEDBY` varchar(120) DEFAULT NULL COMMENT '最后修改人',
  `LASTUPDATEDTIME` datetime DEFAULT NULL COMMENT '最后修改时间',
  `QZRQ` date DEFAULT NULL COMMENT '起租日期',
  `RESERVATION1` varchar(400) DEFAULT NULL COMMENT '保留字段1',
  `RESERVATION2` varchar(400) DEFAULT NULL COMMENT '保留字段2',
  `RESERVATION3` varchar(400) DEFAULT NULL COMMENT '保留字段3',
  `RESERVATION4` varchar(400) DEFAULT NULL COMMENT '保留字段4',
  `RESERVATION5` varchar(400) DEFAULT NULL COMMENT '保留字段5',
  `RESERVATION6` varchar(400) DEFAULT NULL COMMENT '保留字段6',
  `RESERVATION7` varchar(400) DEFAULT NULL COMMENT '保留字段7',
  `RESERVATION8` varchar(400) DEFAULT NULL COMMENT '保留字段8',
  `RESERVATION9` varchar(400) DEFAULT NULL COMMENT '保留字段9',
  `RESERVATION10` varchar(400) DEFAULT NULL COMMENT '保留字段10',
  `RESERVATION11` varchar(400) DEFAULT NULL COMMENT '保留字段11',
  `RESERVATION12` varchar(400) DEFAULT NULL COMMENT '保留字段12',
  `RESERVATION13` varchar(400) DEFAULT NULL COMMENT '保留字段13',
  `RESERVATION14` varchar(400) DEFAULT NULL COMMENT '保留字段14',
  `RESERVATION15` datetime DEFAULT NULL COMMENT '保留字段15',
  `RESERVATION16` datetime DEFAULT NULL COMMENT '保留字段16',
  `RESERVATION17` datetime DEFAULT NULL COMMENT '保留字段17',
  `RESERVATION18` datetime DEFAULT NULL COMMENT '保留字段18',
  `SJDRGXSJ` datetime DEFAULT NULL COMMENT '数据导入更新时间',
  `SJDRSJ` datetime DEFAULT NULL COMMENT '数据导入时间',
  `SJLY` varchar(5) DEFAULT NULL COMMENT '数据来源kind=sjly',
  `SJLY_ZW` varchar(255) DEFAULT NULL,
  `SYSTEMID` varchar(50) NOT NULL COMMENT '主键',
  `TZRQ` date DEFAULT NULL COMMENT '停租日期',
  `UPLOADFLAG` varchar(4) DEFAULT NULL COMMENT '上传标志',
  `WBXTFWZJ` varchar(400) DEFAULT NULL COMMENT '外部系统房屋主键（用于导入数据时记录）',
  `WBXTZJ` varchar(400) DEFAULT NULL COMMENT '外部系统主键（用于导入数据时记录）',
  `YXTBH` varchar(100) DEFAULT NULL COMMENT '原系统编号',
  `ZFRGX` varchar(30) DEFAULT NULL COMMENT '出租人与房主关系kind=gzdx_gxrlx',
  `ZFRGX_ZW` varchar(255) DEFAULT NULL,
  `ZFRGX_GABZ` varchar(50) DEFAULT NULL COMMENT '出租人与房主关系kind=gzdx_gxrlx_公安标准',
  `ZFRLXDH` varchar(30) DEFAULT NULL COMMENT '出租房人联系电话',
  `ZFRXM` varchar(50) DEFAULT NULL COMMENT '出租房人姓名',
  `ZFRYWM` varchar(30) DEFAULT NULL COMMENT '出租房人英文名',
  `ZFRYWX` varchar(30) DEFAULT NULL COMMENT '出租房人英文姓',
  `ZFRZJHM` varchar(30) DEFAULT NULL COMMENT '出租房人证件号码',
  `ZFRZJZL` varchar(20) DEFAULT NULL COMMENT '出租房人证件种类kind=wg_03',
  `ZFRZJZL_ZW` varchar(255) DEFAULT NULL,
  `ZFRZJZL_GABZ` varchar(50) DEFAULT NULL COMMENT '出租房人证件种类kind=wg_03_公安标准',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_sqjw_syrk_ryxxb
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_sqjw_syrk_ryxxb`;
CREATE TABLE `t_bz_sqjw_syrk_ryxxb` (
  `SYSTEMID` varchar(50) NOT NULL COMMENT '系统主键',
  `BFJZDX` varchar(40) DEFAULT NULL COMMENT '帮扶救助对象 ：kind=syrk_bfjzdx',
  `BMCH` varchar(200) DEFAULT NULL COMMENT '别名/绰号',
  `BZ` text COMMENT '备注',
  `CREATEDTIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATOR` varchar(120) DEFAULT NULL COMMENT '创建人',
  `CSRQ` datetime DEFAULT NULL COMMENT '出生日期',
  `CYDWMC` varchar(200) DEFAULT NULL COMMENT '最后一个从业单位名称',
  `CYM` varchar(120) DEFAULT NULL COMMENT '曾用名',
  `CYQK` varchar(80) DEFAULT NULL COMMENT '从业情况',
  `CZBS` varchar(10) DEFAULT NULL COMMENT '常住标识',
  `CZFWBH` varchar(200) DEFAULT NULL COMMENT '出租房屋编号',
  `DELETEFLAG` varchar(4) DEFAULT NULL COMMENT '删除标志',
  `DJDWDM` varchar(80) DEFAULT NULL COMMENT '登记人单位代码 ：sql=select code,detail,spell from v_dictionary_pcs  order by code',
  `DJDWDM_GABZ` varchar(12) DEFAULT NULL COMMENT '登记人单位代码 ：sql=select code,detail,spell from v_dictionary_pcs  order by code_公安标准',
  `DOWNLOADFLAG` varchar(4) DEFAULT NULL COMMENT '下传标志',
  `DRSFYX` varchar(1) DEFAULT NULL COMMENT '导入数据时是否处于有效状态，1有效',
  `DWBH` varchar(128) DEFAULT NULL COMMENT '最后从业单位编号',
  `DWBH_GABZ` varchar(12) DEFAULT NULL COMMENT '最后从业单位编号_公安标准',
  `EMAIL` varchar(200) DEFAULT NULL COMMENT '邮箱',
  `FQ_GMSFZ` varchar(120) DEFAULT NULL COMMENT '父亲_公民身份号码',
  `FQ_WWM` varchar(120) DEFAULT NULL COMMENT '父亲_外文名',
  `FQ_WWX` varchar(120) DEFAULT NULL COMMENT '父亲_外文姓',
  `FQ_XM` varchar(200) DEFAULT NULL COMMENT '父亲_姓名',
  `FQ_ZJHM` varchar(100) DEFAULT NULL COMMENT '父亲_证件号码',
  `FQ_ZJZL` varchar(10) DEFAULT NULL COMMENT '父亲_证件种类kind=wg_03',
  `FWCS` text COMMENT '服务处所',
  `FZ_GMSFZ` varchar(120) DEFAULT NULL COMMENT '房主_公民身份号码',
  `FZ_LXDH` varchar(20) DEFAULT NULL COMMENT '房主_联系电话',
  `FZ_WWM` varchar(120) DEFAULT NULL COMMENT '房主_外文名',
  `FZ_WWX` varchar(120) DEFAULT NULL COMMENT '房主_外文姓',
  `FZ_XM` varchar(200) DEFAULT NULL COMMENT '房主_姓名',
  `FZ_ZJHM` varchar(100) DEFAULT NULL COMMENT '房主_证件号码',
  `FZ_ZJZL` varchar(10) DEFAULT NULL COMMENT '房主_证件种类kind=wg_03',
  `GJ` varchar(40) DEFAULT NULL COMMENT '国籍（地区）：kind=04',
  `GJ_GABZ` varchar(3) DEFAULT NULL COMMENT '国籍（地区）：kind=04_公安标准',
  `GLLB` varchar(40) DEFAULT NULL COMMENT '管理类别 ：sql=select code,detail,spell from dictionary where kind=syrk_gllb and code!=02 ',
  `GXDW` varchar(12) DEFAULT NULL COMMENT '管辖单位代码(派出所代码)',
  `GXDW_GABZ` varchar(12) DEFAULT NULL COMMENT '管辖单位代码(派出所代码)_公安标准',
  `GZDXGLLB` varchar(100) DEFAULT NULL COMMENT '工作对象管理类别',
  `GZDXLGZT` varchar(50) DEFAULT NULL COMMENT '工作对象列管状态字典kind=zddx_0041',
  `GZDXRYFL` varchar(100) DEFAULT NULL COMMENT '工作对象人员分类',
  `GZDXSYSID` varchar(100) DEFAULT NULL COMMENT '工作对象systemid',
  `HCK_GXSJ` datetime DEFAULT NULL COMMENT '更新时间',
  `HCK_RKSJ` datetime DEFAULT NULL COMMENT '入库时间',
  `HID` varchar(200) DEFAULT NULL COMMENT '户id',
  `HJDZ_BZ` varchar(400) DEFAULT NULL COMMENT '户籍地址（标准地址）',
  `HJDZ_BZDZDM` varchar(200) DEFAULT NULL COMMENT '户籍地址（标准地址代码）',
  `HJ_JCWDM` varchar(200) DEFAULT NULL COMMENT '居(村)委_户籍',
  `HJ_PCSDM` varchar(120) DEFAULT NULL COMMENT '派出所_户籍 ：sql=select code,detail,spell from v_dictionary_pcs order by code',
  `HJ_PCSDM_GABZ` varchar(12) DEFAULT NULL COMMENT '派出所_户籍 ：sql=select code,detail,spell from v_dictionary_pcs order by code_公安标准',
  `HJ_SQJWSDM` varchar(120) DEFAULT NULL COMMENT '警务室_户籍 ：sql=select code,detail,spell from v_dictionary_jwq order by code',
  `HJ_XJGAJGDM` varchar(120) DEFAULT NULL COMMENT '所属县级公安机关_户籍 ：sql=select code,detail,spell from v_dictionary_pcs  order by code',
  `HJ_XJGAJGDM_GABZ` varchar(12) DEFAULT NULL COMMENT '所属县级公安机关_户籍 ：sql=select code,detail,spell from v_dictionary_pcs  order by code_公安标准',
  `HJ_XZ` varchar(400) DEFAULT NULL COMMENT '详址_户籍',
  `HJ_XZJDDM` varchar(200) DEFAULT NULL COMMENT '乡镇街道_户籍 ：sql=select code,detail,spell from v_dictionary_xzjd order by code',
  `HJ_XZQHDM` varchar(24) DEFAULT NULL COMMENT '行政区_户籍 ：sql=select code,detail,spell from v_dictionary_xzqh order by code',
  `HJ_XZQHDM_GABZ` varchar(6) DEFAULT NULL COMMENT '行政区_户籍 ：sql=select code,detail,spell from v_dictionary_xzqh order by code_公安标准',
  `HKGLLB` varchar(40) DEFAULT NULL COMMENT '户口管理类别 ：kind=syrk_hs_gllb',
  `HKSZDLX` varchar(10) DEFAULT NULL COMMENT '户口所在地类型kind=syrk_hkszdlx',
  `HYZK` varchar(40) DEFAULT NULL COMMENT '婚姻状况 ：kind=pcs_058',
  `HYZK_GABZ` varchar(2) DEFAULT NULL COMMENT '婚姻状况 ：kind=pcs_058_公安标准',
  `JDDWMC` text COMMENT '接待单位名称',
  `JG` varchar(40) DEFAULT NULL COMMENT '籍贯 ：kind = 07',
  `JG_GABZ` varchar(6) DEFAULT NULL COMMENT '籍贯 ：kind = 07_公安标准',
  `JHR_GMSFZ` varchar(100) DEFAULT NULL COMMENT '监护人_公民身份证号',
  `JHR_JHGX` varchar(10) DEFAULT NULL COMMENT '监护人_监护关系kind=wg_38',
  `JHR_LXDH` varchar(20) DEFAULT NULL COMMENT '监护人_联系电话',
  `JHR_WWM` varchar(200) DEFAULT NULL COMMENT '监护人_外文名',
  `JHR_WWX` varchar(200) DEFAULT NULL COMMENT '监护人_外文姓',
  `JHR_XM` varchar(200) DEFAULT NULL COMMENT '监护人_姓名',
  `JHR_ZJHM` varchar(100) DEFAULT NULL COMMENT '监护人_证件号码',
  `JHR_ZJZL` varchar(10) DEFAULT NULL COMMENT '监护人_证件种类kind=wg_03',
  `JJZK` varchar(40) DEFAULT NULL COMMENT '经济状况',
  `JTGJ` text COMMENT '交通工具',
  `JWRY_GJ` varchar(20) DEFAULT NULL COMMENT '国籍（地区）',
  `JWRY_GJ_GABZ` varchar(3) DEFAULT NULL COMMENT '国籍（地区）_公安标准',
  `JWRY_JWSF` varchar(20) DEFAULT NULL COMMENT '境外身份 ：kind=wg_57',
  `JWRY_RYLB` varchar(20) DEFAULT NULL COMMENT '境外人员类别 ：kind=wg_97',
  `JWRY_TLSY` varchar(20) DEFAULT NULL COMMENT '停留事由 ：kind=wg_24',
  `JWRY_ZHSF` varchar(20) DEFAULT NULL COMMENT '在华身份 ：kind=wg_57',
  `JWRY_ZSLB` varchar(20) DEFAULT NULL COMMENT '住所类型 ：kind=wg_101',
  `JZXX_JLXDM` varchar(200) DEFAULT NULL COMMENT '居住信息街路巷代码',
  `JZXX_MLPDM` varchar(200) DEFAULT NULL COMMENT '居住信息门楼牌代码',
  `LASTUPDATEDBY` varchar(120) DEFAULT NULL COMMENT '最后修改人',
  `LASTUPDATEDDEPT` varchar(100) DEFAULT NULL COMMENT '最后修改单位 ：sql=select code,detail,spell from v_dictionary_pcs',
  `LASTUPDATEDDEPT_GABZ` varchar(12) DEFAULT NULL COMMENT '最后修改单位 ：sql=select code,detail,spell from v_dictionary_pcs_公安标准',
  `LASTUPDATEDTIME` datetime DEFAULT NULL COMMENT '最后修改时间',
  `LBSQK_LZDGJ` varchar(10) DEFAULT NULL COMMENT '来本市情况_来自地国家（地区）kind=04',
  `LBSQK_LZDGJ_GABZ` varchar(3) DEFAULT NULL COMMENT '来本市情况_来自地国家（地区）kind=04_公安标准',
  `LBSQK_LZDSSXQ` varchar(10) DEFAULT NULL COMMENT '来本市情况_来自地省市县（区）kind=07',
  `LBSQK_LZDSSXQ_GABZ` varchar(6) DEFAULT NULL COMMENT '来本市情况_来自地省市县（区）kind=07_公安标准',
  `LBSQK_LZDXZ` varchar(400) DEFAULT NULL COMMENT '来本市情况_来自地详址',
  `LBSQK_LZDXZDM` varchar(100) DEFAULT NULL COMMENT '来本市情况_来自地详址dm',
  `LBSQK_YY` varchar(10) DEFAULT NULL COMMENT '来本市情况_迁移（流动）原因kind=syrk_zzsy',
  `LCZT` varchar(4) DEFAULT NULL COMMENT '流出状态',
  `LKGZLB` varchar(4) DEFAULT NULL COMMENT '流动人口管理类别 ：kind=sqjw_syrk_lkgzlb',
  `LRSJ` datetime DEFAULT NULL COMMENT '流入时间',
  `LSDWMC` text COMMENT '留宿单位名称',
  `LXFS` text COMMENT '联系方式',
  `LXR_GMSFZ` varchar(100) DEFAULT NULL COMMENT '联系人_公民身份号码',
  `LXR_LXDH` varchar(20) DEFAULT NULL COMMENT '联系人_联系电话',
  `LXR_SHGX` varchar(10) DEFAULT NULL COMMENT '联系人_社会关系kind=38',
  `LXR_SSXQ` varchar(10) DEFAULT NULL COMMENT '联系人_省市县（区）',
  `LXR_SSXQ_GABZ` varchar(6) DEFAULT NULL COMMENT '联系人_省市县（区）_公安标准',
  `LXR_WWM` varchar(200) DEFAULT NULL COMMENT '联系人_外文名',
  `LXR_WWX` varchar(200) DEFAULT NULL COMMENT '联系人_外文姓',
  `LXR_XM` varchar(200) DEFAULT NULL COMMENT '联系人_姓名',
  `LXR_XZ` varchar(400) DEFAULT NULL COMMENT '联系人_区划内详细地址',
  `LXR_XZDM` varchar(40) DEFAULT NULL COMMENT '联系人_区划内详细地址dm',
  `LXR_ZJHM` varchar(100) DEFAULT NULL COMMENT '联系人_证件号码',
  `LXR_ZJZL` varchar(10) DEFAULT NULL COMMENT '联系人_证件种类kind=wg_03',
  `LZGJ` varchar(10) DEFAULT NULL COMMENT '来自地国家（地区）',
  `MQ_GMSFZ` varchar(120) DEFAULT NULL COMMENT '母亲_公民身份号码',
  `MQ_WWM` varchar(120) DEFAULT NULL COMMENT '母亲_外文名',
  `MQ_WWX` varchar(120) DEFAULT NULL COMMENT '母亲_外文姓',
  `MQ_XM` varchar(200) DEFAULT NULL COMMENT '母亲_姓名',
  `MQ_ZJHM` varchar(100) DEFAULT NULL COMMENT '母亲_证件号码',
  `MQ_ZJZL` varchar(10) DEFAULT NULL COMMENT '母亲_证件种类kind=wg_03',
  `MZ` varchar(40) DEFAULT NULL COMMENT '民族kind=05',
  `MZ_GABZ` varchar(2) DEFAULT NULL COMMENT '民族kind=05_公安标准',
  `NLKRQ` datetime DEFAULT NULL COMMENT '拟离开日期',
  `PO_GMSFZ` varchar(120) DEFAULT NULL COMMENT '配偶_公民身份号码',
  `PO_WWM` varchar(120) DEFAULT NULL COMMENT '配偶_外文名',
  `PO_WWX` varchar(120) DEFAULT NULL COMMENT '配偶_外文姓',
  `PO_XM` varchar(200) DEFAULT NULL COMMENT '配偶_姓名',
  `PO_ZJHM` varchar(100) DEFAULT NULL COMMENT '配偶_证件号码',
  `PO_ZJZL` varchar(10) DEFAULT NULL COMMENT '配偶_证件种类kind=wg_03',
  `QQ` varchar(80) DEFAULT NULL COMMENT 'qq',
  `QWGJ` varchar(10) DEFAULT NULL COMMENT '去往地国家（地区）',
  `QWGJ_GABZ` varchar(3) DEFAULT NULL COMMENT '去往地国家（地区）_公安标准',
  `QWSSXQ` varchar(10) DEFAULT NULL COMMENT '去往地省市县（区）',
  `QWSSXQ_GABZ` varchar(6) DEFAULT NULL COMMENT '去往地省市县（区）_公安标准',
  `QWXZ` text COMMENT '去往地详细地址',
  `QWXZDM` varchar(300) DEFAULT NULL COMMENT '去往地详细地址dm',
  `QYFW` varchar(10) DEFAULT NULL COMMENT '区域范围kind=syrk_qyfw',
  `QZJLXKH` varchar(100) DEFAULT NULL COMMENT '签证（居留许可）号',
  `QZJLZL` varchar(10) DEFAULT NULL COMMENT '签证（居留许可）种类kind=wg_09',
  `QZJZJZRQ` date DEFAULT NULL COMMENT '签证（居留许可）截止日期',
  `QZQFJG` varchar(12) DEFAULT NULL COMMENT '签证（居留许可）签发机关',
  `QZTLRQ` date DEFAULT NULL COMMENT '签证停（居）留日期',
  `RESERVATION01` varchar(200) DEFAULT NULL COMMENT '不注销原因',
  `RESERVATION02` varchar(80) DEFAULT NULL COMMENT '政治面貌kind=118',
  `RESERVATION03` varchar(80) DEFAULT NULL COMMENT '暂住事由',
  `RESERVATION04` date DEFAULT NULL COMMENT '来本市日期',
  `RESERVATION05` varchar(200) DEFAULT NULL COMMENT '现居地详址编码',
  `RESERVATION06` varchar(80) DEFAULT NULL COMMENT '保留字段6',
  `RESERVATION07` varchar(80) DEFAULT NULL COMMENT '保留字段7',
  `RESERVATION08` varchar(80) DEFAULT NULL COMMENT '保留字段8',
  `RESERVATION09` varchar(80) DEFAULT NULL COMMENT '数据转换更新字段',
  `RESERVATION10` varchar(80) DEFAULT NULL COMMENT '对应实口户号',
  `RESERVATION11` date DEFAULT NULL COMMENT '保留字段11',
  `RESERVATION12` date DEFAULT NULL COMMENT '保留字段12',
  `RESERVATION13` date DEFAULT NULL COMMENT '保留字段13',
  `RESERVATION14` varchar(40) DEFAULT NULL COMMENT '保留字段14',
  `RESERVATION15` varchar(40) DEFAULT NULL COMMENT '保留字段15',
  `RESERVATION16` varchar(40) DEFAULT NULL COMMENT '保留字段16',
  `RESERVATION17` varchar(40) DEFAULT NULL COMMENT '保留字段17',
  `RESERVATION18` varchar(40) DEFAULT NULL COMMENT '保留字段18',
  `RESERVATION19` varchar(40) DEFAULT NULL COMMENT '保留字段19',
  `RESERVATION20` varchar(40) DEFAULT NULL COMMENT '保留字段20',
  `RESERVATION21` varchar(40) DEFAULT NULL COMMENT '保留字段21',
  `RESERVATION22` varchar(40) DEFAULT NULL COMMENT '保留字段22',
  `RESERVATION23` varchar(40) DEFAULT NULL COMMENT '保留字段23',
  `RESERVATION24` varchar(40) DEFAULT NULL COMMENT '保留字段24',
  `RESERVATION25` varchar(40) DEFAULT NULL COMMENT '保留字段25',
  `RESERVATION26` varchar(40) DEFAULT NULL COMMENT '保留字段26',
  `RESERVATION27` varchar(40) DEFAULT NULL COMMENT '保留字段27',
  `RESERVATION28` date DEFAULT NULL COMMENT '保留字段28',
  `RESERVATION29` date DEFAULT NULL COMMENT '保留字段29',
  `RESERVATION30` date DEFAULT NULL COMMENT '保留字段30',
  `RID` varchar(100) DEFAULT NULL COMMENT '人员id(外系统人员编号)',
  `RJKA` varchar(10) DEFAULT NULL COMMENT '入境口岸',
  `RJRQ` datetime DEFAULT NULL COMMENT '入境日期',
  `RKZXLB` varchar(12) DEFAULT NULL COMMENT '注销类别kind=syrk_zxlb',
  `RYLB` varchar(120) DEFAULT NULL COMMENT '人员类别 ：kind=syrk_rylb',
  `SBR_GMSFZ` varchar(120) DEFAULT NULL COMMENT '申报人_公民身份号码',
  `SBR_WWM` varchar(120) DEFAULT NULL COMMENT '申报人_外文名',
  `SBR_WWX` varchar(120) DEFAULT NULL COMMENT '申报人_外文姓',
  `SBR_XM` varchar(200) DEFAULT NULL COMMENT '申报人_姓名',
  `SBR_ZJHM` varchar(100) DEFAULT NULL COMMENT '申报人_证件号码',
  `SBR_ZJZL` varchar(100) DEFAULT NULL COMMENT '申报人_证件种类kind=wg_03',
  `SFGLDZ` varchar(4) DEFAULT NULL COMMENT '是否关联地址',
  `SFHS` varchar(1) DEFAULT NULL COMMENT '是否核实kind = 00',
  `SFMGRY` varchar(4) DEFAULT NULL COMMENT '是否敏感人员 ：sql=select 1 code, detail,spell from dual',
  `SFQBZDRY` varchar(4) DEFAULT NULL COMMENT '是否情报重点人员',
  `SFXJR` varchar(2) DEFAULT NULL COMMENT '是否新疆人kind=00',
  `SFYX` varchar(8) DEFAULT NULL COMMENT '是否有效1有效0无效',
  `SFZAZDR` varchar(2) DEFAULT NULL COMMENT '是否治安重点人kind=00',
  `SFZDBHRY` varchar(20) DEFAULT NULL COMMENT '是否重点保护人员 ：kind=sqjw_tsry',
  `SG` int(11) DEFAULT NULL COMMENT '身高cm',
  `SJDRGXSJ` date DEFAULT NULL COMMENT '数据导入更新时间',
  `SJDRSJ` date DEFAULT NULL COMMENT '导入时间',
  `SJLY` varchar(40) DEFAULT NULL COMMENT '数据来源 :1常口导入，2流口导入、3境外人员导入、4从业人员导入、5工作对象导入、8、移动端采集，9、内网采集',
  `SSDS` varchar(8) DEFAULT NULL COMMENT '所属地市',
  `SYRKBH` varchar(200) DEFAULT NULL COMMENT '实有人口编号，生成规则f_get_syrkbh()',
  `YXTBH` varchar(200) DEFAULT NULL COMMENT '主键',
  `TC` text COMMENT '特长 ：kind=10',
  `UPLOADFLAG` varchar(4) DEFAULT NULL COMMENT '上传标志',
  `WBXTFWZJ` varchar(100) DEFAULT NULL COMMENT '外部系统房屋主键',
  `WHCD` varchar(40) DEFAULT NULL COMMENT '文化程度 ：kind=02',
  `WHCD_GABZ` varchar(20) DEFAULT NULL COMMENT '文化程度 ：kind=02_公安标准',
  `XB` varchar(8) DEFAULT NULL COMMENT '性别 ：kind=01',
  `XB_GABZ` varchar(1) DEFAULT NULL COMMENT '性别 ：kind=01_公安标准',
  `XJD_JCWDM` varchar(200) DEFAULT NULL COMMENT '居(村)委_现居地',
  `XJD_PCSDM` varchar(120) DEFAULT NULL COMMENT '派出所_现居地 ：sql=select code,detail,spell from v_dictionary_pcs order by code',
  `XJD_PCSDM_GABZ` varchar(12) DEFAULT NULL COMMENT '派出所_现居地 ：sql=select code,detail,spell from v_dictionary_pcs order by code_公安标准',
  `XJD_SQJWSDM` varchar(120) DEFAULT NULL COMMENT '市区警务室_现居地 ：sql=select code,detail,spell from v_dictionary_jwq order by code',
  `XJD_SSJMXQDM` varchar(200) DEFAULT NULL COMMENT '所属居民小区代码_现居地',
  `XJD_XZ` text COMMENT '详址_现居地(关联标准地址)',
  `XJD_XZDM` varchar(200) DEFAULT NULL COMMENT '详址代码_现居地',
  `XJD_XZJDDM` varchar(200) DEFAULT NULL COMMENT '乡镇街道_现居地 ：sql=select code,detail,spell from v_dictionary_xzjd order by code',
  `XJD_XZQHDM` varchar(24) DEFAULT NULL COMMENT '行政区_现居地 ：sql=select code,detail,spell from v_dictionary_xzqh order by code',
  `XJD_XZQHDM_GABZ` varchar(6) DEFAULT NULL COMMENT '行政区_现居地 ：sql=select code,detail,spell from v_dictionary_xzqh order by code_公安标准',
  `XJR_DDDLXRGJ` text COMMENT '新疆人信息_到达地主要联系人及通讯工具',
  `XJR_DNABH` varchar(100) DEFAULT NULL COMMENT '新疆人信息_dna编号',
  `XJR_QWD` text COMMENT '新疆人信息_去往地',
  `XJR_SHGXQK` text COMMENT '新疆人信息_主要社会关系人情况',
  `XJR_TXGJ` text COMMENT '新疆人信息_通讯工具（含网上和网下）',
  `XJR_XKKYJX` text COMMENT '新疆人信息_涉恐可疑迹象kind=syrk_skkyjx',
  `XJR_XKKYXW` text COMMENT '新疆人信息_涉恐可疑行为kind=syrk_skkyxx',
  `XJR_ZZWBH` varchar(100) DEFAULT NULL COMMENT '新疆人信息_指掌纹编号',
  `XM` varchar(120) DEFAULT NULL COMMENT '中文姓名',
  `XMPY` varchar(200) DEFAULT NULL COMMENT '姓名拼音',
  `XX` varchar(40) DEFAULT NULL COMMENT '血型',
  `XXJB` varchar(8) DEFAULT NULL COMMENT '信息级别',
  `YHJXZ` varchar(400) DEFAULT NULL COMMENT '原户籍详细地址',
  `YHZGX` varchar(16) DEFAULT NULL COMMENT '与户主关系',
  `YWM` text COMMENT '英文名',
  `YWX` text COMMENT '英文姓',
  `YZDXZ` varchar(400) DEFAULT NULL COMMENT '原住地详细地址',
  `ZDRYBH` varchar(200) DEFAULT NULL COMMENT '重点人员编号（重口人员数据过来标识）',
  `ZDRYLB` varchar(200) DEFAULT NULL COMMENT '重点人员类别 ：kind=zdry_zdrylbbj',
  `ZJHM` varchar(120) DEFAULT NULL COMMENT '证件号码/身份证号',
  `ZJJZRQ` date DEFAULT NULL COMMENT '证件截止日期',
  `ZJXY` varchar(200) DEFAULT NULL COMMENT '宗教信仰',
  `ZJZL` varchar(40) DEFAULT NULL COMMENT '证件种类 ：kind=wg_03',
  `ZMRS` varchar(40) DEFAULT NULL COMMENT '知名人士 ：kind=syrk_zmrs',
  `ZPZT` varchar(80) DEFAULT NULL COMMENT '数据转换-照片状态',
  `ZSRQ` date DEFAULT NULL COMMENT '住宿日期',
  `ZXDW` varchar(12) DEFAULT NULL COMMENT '注销单位',
  `ZXDW_GABZ` varchar(12) DEFAULT NULL COMMENT '注销单位_公安标准',
  `ZXR` varchar(50) DEFAULT NULL COMMENT '注销人',
  `ZXSJ` date DEFAULT NULL COMMENT '注销时间',
  `ZXZT` varchar(1) DEFAULT NULL COMMENT '注销状态kind=00',
  `ZY` varchar(200) DEFAULT NULL COMMENT '职业',
  `ZYLB` varchar(120) DEFAULT NULL COMMENT '职业类别 ：kind=sqjw_czrk_zylb',
  `ZZCS` varchar(4) DEFAULT NULL COMMENT '暂住处所 ：kind = zk_002',
  `ZZSY` varchar(10) DEFAULT NULL COMMENT '暂住事由 ：kind = zk_003',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_sqjw_zdry_zdrkjtcy
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_sqjw_zdry_zdrkjtcy`;
CREATE TABLE `t_bz_sqjw_zdry_zdrkjtcy` (
  `SYSTEMID` varchar(50) NOT NULL COMMENT '系统主键',
  `BZ` text COMMENT '备注(..ul)',
  `CSD` varchar(30) DEFAULT NULL COMMENT '出生地省市县(c6)',
  `CSD_GABZ` varchar(6) DEFAULT NULL COMMENT '出生地省市县(c6)_公安标准',
  `CSDGJ` varchar(30) DEFAULT NULL COMMENT '出生地国家(c3)',
  `CSDGJ_GABZ` varchar(3) DEFAULT NULL COMMENT '出生地国家(c3)_公安标准',
  `CSRQ` date DEFAULT NULL COMMENT '出生日期(d8（yyyymmdd）)',
  `CYM` varchar(300) DEFAULT NULL COMMENT '曾用名/绰号(c..50)',
  `DJDW` varchar(60) DEFAULT NULL COMMENT '登记单位(c9)',
  `DJDW_GABZ` varchar(12) DEFAULT NULL COMMENT '登记单位(c9)_公安标准',
  `DJMJJH` varchar(36) DEFAULT NULL COMMENT '登记民警号',
  `DJR` varchar(150) DEFAULT NULL COMMENT '登记人(c..50)',
  `DJSJ` datetime DEFAULT NULL COMMENT '登记时间(d14(yyyymmddhhmmss))',
  `FWCS` varchar(1200) DEFAULT NULL COMMENT '服务处所(c..100)',
  `GJ` varchar(30) DEFAULT NULL COMMENT '籍贯国家(c3)',
  `GJ_GABZ` varchar(3) DEFAULT NULL COMMENT '籍贯国家(c3)_公安标准',
  `GX` varchar(30) DEFAULT NULL COMMENT '关系(c2)',
  `HCK_GXSJ` datetime DEFAULT NULL,
  `HCK_RKSJ` datetime DEFAULT NULL,
  `JG` varchar(30) DEFAULT NULL COMMENT '籍贯省市县(c6)',
  `JG_GABZ` varchar(6) DEFAULT NULL COMMENT '籍贯省市县(c6)_公安标准',
  `JZDSSX` varchar(30) DEFAULT NULL COMMENT '居住地省市县(c6)',
  `JZDSSX_GABZ` varchar(6) DEFAULT NULL COMMENT '居住地省市县(c6)_公安标准',
  `LXDH` varchar(300) DEFAULT NULL COMMENT '联系电话(c..18)',
  `MZ` varchar(6) DEFAULT NULL COMMENT '民族 (c2)',
  `MZ_GABZ` varchar(2) DEFAULT NULL COMMENT '民族 (c2)_公安标准',
  `RK_JBXX_ID` varchar(255) DEFAULT NULL,
  `RK_JTCY_ID` varchar(11) DEFAULT NULL,
  `SJDRGXSJ` datetime DEFAULT NULL,
  `SJDRSJ` datetime DEFAULT NULL,
  `SJJZXZ` varchar(1800) DEFAULT NULL COMMENT '实际居住详址(c..100)',
  `SJJZXZDM` varchar(90) DEFAULT NULL,
  `SJLY` varchar(15) DEFAULT NULL COMMENT '数据来源',
  `YXTBH` varchar(150) DEFAULT NULL COMMENT '系统编号',
  `WWM` varchar(300) DEFAULT NULL COMMENT '外文名(c..40)',
  `WWX` varchar(300) DEFAULT NULL COMMENT '外文姓(c..40)',
  `XB` varchar(3) DEFAULT NULL COMMENT '性别(c1)',
  `XB_GABZ` varchar(1) DEFAULT NULL COMMENT '性别(c1)_公安标准',
  `XGDW` varchar(60) DEFAULT NULL COMMENT '最后修改单位(c9)',
  `XGDW_GABZ` varchar(12) DEFAULT NULL COMMENT '最后修改单位(c9)_公安标准',
  `XGR` varchar(150) DEFAULT NULL COMMENT '最后修改人(c..50)',
  `XGSJ` datetime DEFAULT NULL COMMENT '最后修改时间(d14(yyyymmddhhmmss))',
  `XM` varchar(300) DEFAULT NULL COMMENT '姓名(c..50)',
  `ZBID` varchar(150) DEFAULT NULL COMMENT '主表系统编号',
  `ZJHM` varchar(300) DEFAULT NULL COMMENT '公民身份证号(c18)',
  `ZJZL` varchar(15) DEFAULT NULL COMMENT '证件种类(c3)',
  `ZXZT` varchar(3) DEFAULT NULL COMMENT '是否注销',
  `ZZ` varchar(1200) DEFAULT NULL COMMENT '住址(c..100)',
  `ZZDM` varchar(90) DEFAULT NULL COMMENT '住址dm 标准地址代码',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_sqjw_zdry_zdrkjwryxx
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_sqjw_zdry_zdrkjwryxx`;
CREATE TABLE `t_bz_sqjw_zdry_zdrkjwryxx` (
  `SYSTEMID` varchar(50) NOT NULL COMMENT '系统主键',
  `BZ` text COMMENT '备注(..ul)',
  `CSDGJ` varchar(30) DEFAULT NULL COMMENT '出生地国家(c3)',
  `CSDGJ_GABZ` varchar(3) DEFAULT NULL COMMENT '出生地国家(c3)_公安标准',
  `CSDSSX` varchar(30) DEFAULT NULL COMMENT '出生地省市县(c6)',
  `CSDSSX_GABZ` varchar(6) DEFAULT NULL COMMENT '出生地省市县(c6)_公安标准',
  `CSRQ` date DEFAULT NULL COMMENT '出生日期(d8（yyyymmdd）)',
  `CYM` varchar(300) DEFAULT NULL COMMENT '曾用名(c..50)',
  `DJDW` varchar(60) DEFAULT NULL COMMENT '登记单位(c9)',
  `DJDW_GABZ` varchar(12) DEFAULT NULL COMMENT '登记单位(c9)_公安标准',
  `DJMJJH` varchar(36) DEFAULT NULL COMMENT '登记民警号',
  `DJR` varchar(150) DEFAULT NULL COMMENT '登记人(c..50)',
  `DJSJ` datetime DEFAULT NULL COMMENT '登记时间(d14(yyyymmddhhmmss))',
  `FWCS` varchar(1200) DEFAULT NULL COMMENT '服务处所(c..100)',
  `GJ` varchar(30) DEFAULT NULL COMMENT '籍贯国家(c3)',
  `GJ_GABZ` varchar(3) DEFAULT NULL COMMENT '籍贯国家(c3)_公安标准',
  `GX` varchar(30) DEFAULT NULL COMMENT '关系',
  `GXLX` varchar(30) DEFAULT NULL COMMENT '关系类型',
  `GZDX_JWRY_ID` decimal(20,0) DEFAULT NULL,
  `HCK_GXSJ` datetime DEFAULT NULL,
  `HCK_RKSJ` datetime DEFAULT NULL,
  `JG` varchar(30) DEFAULT NULL COMMENT '籍贯省市县(c6)',
  `JG_GABZ` varchar(6) DEFAULT NULL COMMENT '籍贯省市县(c6)_公安标准',
  `LXDH` varchar(300) DEFAULT NULL COMMENT '联系电话(c..18)',
  `MZ` varchar(6) DEFAULT NULL COMMENT '民族 (c2)',
  `MZ_GABZ` varchar(2) DEFAULT NULL,
  `RK_JBXX_ID` decimal(20,0) DEFAULT NULL,
  `SJDRGXSJ` datetime DEFAULT NULL,
  `SJDRSJ` datetime DEFAULT NULL,
  `SJJZDSSX` varchar(30) DEFAULT NULL COMMENT '实际居住地省市县(c6)',
  `SJJZDSSX_GABZ` varchar(6) DEFAULT NULL COMMENT '实际居住地省市县(c6)_公安标准',
  `SJJZDXZ` varchar(1200) DEFAULT NULL COMMENT '实际居住地详址(c..100)',
  `SJJZDXZDM` varchar(90) DEFAULT NULL COMMENT '实际居住地详址dm(c36，********-****-****-****-************)',
  `SJLY` varchar(15) DEFAULT NULL COMMENT '数据来源(c12)',
  `YXTBH` varchar(150) DEFAULT NULL COMMENT '系统编号',
  `WWM` varchar(300) DEFAULT NULL COMMENT '外文名(c..40)',
  `WWX` varchar(300) DEFAULT NULL COMMENT '外文姓(c..40)',
  `XB` varchar(3) DEFAULT NULL COMMENT '性别(c1)',
  `XB_GABZ` varchar(1) DEFAULT NULL COMMENT '性别(c1)_公安标准',
  `XGDW` varchar(60) DEFAULT NULL COMMENT '最后修改单位(c9)',
  `XGDW_GABZ` varchar(12) DEFAULT NULL COMMENT '最后修改单位(c9)_公安标准',
  `XGR` varchar(150) DEFAULT NULL COMMENT '最后修改人(c..50)',
  `XGSJ` datetime DEFAULT NULL COMMENT '最后修改时间(d14(yyyymmddhhmmss))',
  `XM` varchar(300) DEFAULT NULL COMMENT '姓名(c..50)',
  `ZBID` varchar(255) DEFAULT NULL COMMENT '主表系统编号',
  `ZJHM` varchar(300) DEFAULT NULL COMMENT '公民身份证号(c18)',
  `ZJZL` varchar(15) DEFAULT NULL COMMENT '证件种类(c3)',
  `ZXZT` varchar(3) DEFAULT NULL COMMENT '是否注销',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_sqjw_zdry_zdrkshgx
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_sqjw_zdry_zdrkshgx`;
CREATE TABLE `t_bz_sqjw_zdry_zdrkshgx` (
  `SYSTEMID` varchar(50) DEFAULT NULL COMMENT '系统主键',
  `BMCH` varchar(360) DEFAULT NULL COMMENT '别名绰号',
  `BZ` text COMMENT '备注(..ul)',
  `CSDGJ` varchar(36) DEFAULT NULL COMMENT '出生地国家(c3)',
  `CSDGJ_GABZ` varchar(3) DEFAULT NULL COMMENT '出生地国家(c3)_公安标准',
  `CSDSSX` varchar(18) DEFAULT NULL COMMENT '出生地省市县(c6)',
  `CSDSSX_GABZ` varchar(6) DEFAULT NULL COMMENT '出生地省市县(c6)_公安标准',
  `CSRQ` date DEFAULT NULL COMMENT '出生日期(d8（yyyymmdd）)',
  `CYDW` varchar(360) DEFAULT NULL COMMENT '就读/就业单位(c..100)',
  `CYM` varchar(360) DEFAULT NULL COMMENT '别名绰号(c..50)',
  `DHHM` varchar(360) DEFAULT NULL COMMENT '电话号码',
  `DJDW` varchar(60) DEFAULT NULL COMMENT '登记单位(c9)',
  `DJDW_GABZ` varchar(12) DEFAULT NULL COMMENT '登记单位(c9)_公安标准',
  `DJR` varchar(150) DEFAULT NULL COMMENT '登记人(c..50)',
  `DJSJ` datetime DEFAULT NULL COMMENT '登记时间(d14(yyyymmddhhmmss))',
  `FWCS` varchar(1200) DEFAULT NULL COMMENT '服务处所(c..100)',
  `GJ` varchar(30) DEFAULT NULL COMMENT '籍贯国家(c3)',
  `GJ_GABZ` varchar(3) DEFAULT NULL COMMENT '籍贯国家(c3)_公安标准',
  `GX` varchar(6) DEFAULT NULL COMMENT '关系',
  `GXLX` varchar(15) DEFAULT NULL COMMENT '关系类型',
  `GZDX_SHGX_ID` decimal(20,0) DEFAULT NULL,
  `HCK_GXSJ` datetime DEFAULT NULL,
  `HCK_RKSJ` datetime DEFAULT NULL,
  `JG` varchar(30) DEFAULT NULL COMMENT '籍贯省市县kind=07(c6)',
  `JG_GABZ` varchar(6) DEFAULT NULL COMMENT '籍贯省市县kind=07(c6)_公安标准',
  `JWZWQDM` varchar(45) DEFAULT NULL COMMENT '警务责任区(c12)',
  `JZDSSX` varchar(30) DEFAULT NULL COMMENT '居住地省市县(c6)',
  `JZDSSX_GABZ` varchar(6) DEFAULT NULL COMMENT '居住地省市县(c6)_公安标准',
  `LXDH` varchar(360) DEFAULT NULL COMMENT '电话号码(c..18)',
  `MZ` varchar(150) DEFAULT NULL COMMENT '民族(c2)',
  `MZ_GABZ` varchar(2) DEFAULT NULL COMMENT '民族(c2)_公安标准',
  `PCSDM` varchar(36) DEFAULT NULL COMMENT '派出所代码(c9)',
  `PCSDM_GABZ` varchar(12) DEFAULT NULL COMMENT '派出所代码(c9)_公安标准',
  `RK_JBXX_ID` decimal(20,0) DEFAULT NULL,
  `SHGX` varchar(15) DEFAULT NULL COMMENT '社会关系',
  `SJDRGXSJ` datetime DEFAULT NULL,
  `SJDRSJ` datetime DEFAULT NULL,
  `SJJZDXZ` varchar(1200) DEFAULT NULL COMMENT '实际居住详址(c..100)',
  `SJJZDXZDM` varchar(90) DEFAULT NULL COMMENT '实际居住详址dm(c36，********-****-****-****-************)',
  `SJLY` varchar(15) DEFAULT NULL COMMENT '数据来源(c12)',
  `SSXQ` varchar(18) DEFAULT NULL COMMENT '所属县区(c6)',
  `SSXQ_GABZ` varchar(6) DEFAULT NULL COMMENT '所属县区(c6)_公安标准',
  `YXTBH` varchar(150) DEFAULT NULL COMMENT '系统编号',
  `WWM` varchar(300) DEFAULT NULL COMMENT '外文名(c..40)',
  `WWX` varchar(300) DEFAULT NULL,
  `XB` varchar(6) DEFAULT NULL COMMENT '性别(c1)',
  `XB_GABZ` varchar(1) DEFAULT NULL COMMENT '性别(c1)_公安标准',
  `XGDW` varchar(60) DEFAULT NULL COMMENT '最后修改单位(c9)',
  `XGDW_GABZ` varchar(12) DEFAULT NULL COMMENT '最后修改单位(c9)_公安标准',
  `XGR` varchar(150) DEFAULT NULL COMMENT '最后修改人(c..50)',
  `XGSJ` datetime DEFAULT NULL COMMENT '最后修改时间(d14(yyyymmddhhmmss))',
  `XM` varchar(150) DEFAULT NULL COMMENT '姓名(c..50)',
  `XZ` varchar(1200) DEFAULT NULL COMMENT '详址(c..100)',
  `XZJDDM` varchar(27) DEFAULT NULL COMMENT '乡镇街道(c3)',
  `YWWFFZQK` varchar(3) DEFAULT NULL COMMENT '有无违法犯罪前科(c6)',
  `ZDRKID` varchar(150) DEFAULT NULL COMMENT '重点人口系统编号(c..40)',
  `ZJHM` varchar(150) DEFAULT NULL COMMENT '证件号码(c..30)',
  `ZJZL` varchar(15) DEFAULT NULL COMMENT '证件种类(c3)',
  `ZXZT` varchar(3) DEFAULT NULL COMMENT '是否注销',
  `ZYLB` varchar(15) DEFAULT NULL COMMENT '职业列种类(c3)',
  `ZZ` varchar(1200) DEFAULT NULL COMMENT '住址(c..100)',
  `ZZDM` varchar(90) DEFAULT NULL COMMENT '住址dm(c6)',
  `ZZDM_GABZ` varchar(6) DEFAULT NULL COMMENT '住址dm(c6)_公安标准',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_sqjw_zdry_zdrkxx
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_sqjw_zdry_zdrkxx`;
CREATE TABLE `t_bz_sqjw_zdry_zdrkxx` (
  `SYSTEMID` varchar(50) NOT NULL COMMENT '系统编号',
  `BMCH` varchar(100) DEFAULT NULL COMMENT '别名绰号',
  `CSD` varchar(10) DEFAULT NULL COMMENT '出生地',
  `CSD_GABZ` varchar(6) DEFAULT NULL COMMENT '出生地(c6)_公安标准',
  `CSRQ` date DEFAULT NULL COMMENT '出生日期',
  `DJDW` varchar(20) DEFAULT NULL COMMENT '登记单位',
  `DJDW_GABZ` varchar(12) DEFAULT NULL COMMENT '登记单位(c9)_公安标准',
  `DJR` varchar(50) DEFAULT NULL COMMENT '登记人',
  `DJSJ` date DEFAULT NULL COMMENT '登记时间',
  `FLJB` varchar(100) DEFAULT NULL COMMENT '分类级别(kind=zdrk_fljb)',
  `FWCS` varchar(400) DEFAULT NULL COMMENT '服务处所',
  `GLLB` varchar(4) DEFAULT NULL COMMENT '管理类别(kind=zdrk_gllb)',
  `GZDX_JBXX_ID` decimal(20,0) DEFAULT NULL,
  `GZRQ` date DEFAULT NULL COMMENT '关注日期',
  `GZYY` varchar(1000) DEFAULT NULL COMMENT '关注原因',
  `HCK_GXSJ` date DEFAULT NULL,
  `HCK_RKSJ` date DEFAULT NULL,
  `HJDPCSDM` varchar(50) DEFAULT NULL COMMENT '户籍地派出所代码',
  `HJDSSXQ` varchar(6) DEFAULT NULL COMMENT '户籍地省市县区(kind=07)',
  `HJDXZDM` varchar(30) DEFAULT NULL COMMENT '户籍地详址代码(标准地址代码)',
  `HJDXZMC` varchar(400) DEFAULT NULL COMMENT '户籍地详址全称',
  `HSSJ` datetime DEFAULT NULL COMMENT '核实时间',
  `HYKY` varchar(10) DEFAULT NULL COMMENT '汉语口音(kind=''11'')',
  `JG` varchar(10) DEFAULT NULL COMMENT '籍贯(kind=07)',
  `JG_GABZ` varchar(6) DEFAULT NULL COMMENT '籍贯(c6)_公安标准',
  `JGRQ` date DEFAULT NULL COMMENT '监管日期',
  `JGYY` varchar(2) DEFAULT NULL COMMENT '监管原因kind=zdrk_jgyy',
  `JYQK` varchar(4) DEFAULT NULL COMMENT '就业情况kind=zdrk_wfjyqk',
  `LXDH` varchar(100) DEFAULT NULL COMMENT '联系电话',
  `MZ` varchar(2) DEFAULT NULL COMMENT '民族(kind=05)',
  `MZ_GABZ` varchar(2) DEFAULT NULL COMMENT '民族(c2)_公安标准',
  `RK_JBXX_ID` decimal(20,0) DEFAULT NULL,
  `SFSDCLG` varchar(1) DEFAULT NULL COMMENT '是否双/多列管(kind=00)',
  `SJDRGXSJ` datetime DEFAULT NULL COMMENT '''数据导入时间''',
  `SJDRSJ` datetime DEFAULT NULL,
  `SJLY` varchar(5) DEFAULT NULL COMMENT '数据来源(kind=sjly，默认为本系统新增)',
  `SSJWQDM` varchar(15) DEFAULT NULL COMMENT '所属警务区',
  `SSPCSDM` varchar(12) DEFAULT NULL COMMENT '所属派出所',
  `SSPCSDM_GABZ` varchar(12) DEFAULT NULL COMMENT '所属派出所(c9)_公安标准',
  `SSSQDM` varchar(12) DEFAULT NULL COMMENT '所属社区',
  `SYRKBH` varchar(50) DEFAULT NULL COMMENT '实有人口编号',
  `YXTBH` varchar(50) DEFAULT NULL COMMENT '系统编号',
  `WHCD` varchar(2) DEFAULT NULL COMMENT '文化程度(kind=02)',
  `WHCD_GABZ` varchar(20) DEFAULT NULL COMMENT '文化程度(c2)_公安标准',
  `XB` varchar(1) DEFAULT NULL COMMENT '性别(kind=01)',
  `XB_GABZ` varchar(1) DEFAULT NULL COMMENT '性别(c1)_公安标准',
  `XCHSJJ` datetime DEFAULT NULL COMMENT '本期核实截止时间',
  `XGDW` varchar(20) DEFAULT NULL COMMENT '最后修改单位',
  `XGDW_GABZ` varchar(12) DEFAULT NULL COMMENT '最后修改单位(c9)_公安标准',
  `XGR` varchar(50) DEFAULT NULL COMMENT '最后修改人',
  `XGSJ` datetime DEFAULT NULL COMMENT '最后修改时间',
  `XJDPCSDM` varchar(50) DEFAULT NULL COMMENT '现住地派出所代码',
  `XJDPCSDM_GABZ` varchar(12) DEFAULT NULL COMMENT '现住地派出所代码(c9)_公安标准',
  `XJDSSXQ` varchar(6) DEFAULT NULL COMMENT '现住地省市县区(kind=07)',
  `XJDXZDM` varchar(30) DEFAULT NULL COMMENT '现住地详址代码(标准地址代码)',
  `XJDXZMC` varchar(400) DEFAULT NULL COMMENT '现住地详址全称',
  `XM` varchar(100) DEFAULT NULL COMMENT '姓名',
  `XXQK` varchar(4) DEFAULT NULL COMMENT '学习情况kind=zdrk_xxqk',
  `YWSJLY` varchar(4) DEFAULT NULL COMMENT '业务数据来源(kind=zdrk_ywsjly)',
  `ZC` varchar(10) DEFAULT NULL COMMENT '专长(varchar2(10))',
  `ZDRYDL` varchar(2) DEFAULT NULL COMMENT '治安重点人大类，kind=zdrk_rydl(01重点人口，02被剥夺政治权利罪犯，03其他治安重点人)',
  `ZJHM` varchar(100) DEFAULT NULL COMMENT '证件号码',
  `ZJZL` varchar(5) DEFAULT NULL COMMENT '证件种类(kind=wg_03，默认为身份证)',
  `ZRMJ` varchar(50) DEFAULT NULL COMMENT '社区责任民警',
  `ZRMJDH` varchar(100) DEFAULT NULL COMMENT '责任民警电话',
  `ZT` varchar(4) DEFAULT NULL COMMENT '状态(kind=zdrk_zt，默认值为未提交)',
  `ZXZT` varchar(1) DEFAULT NULL COMMENT '是否注销(kind=00)',
  `ZY` varchar(6) DEFAULT NULL COMMENT '职业(kind=sqjw_czrk_zylb)',
  `ZYWT` text COMMENT '主要问题',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
