/*
Navicat MySQL Data Transfer

Source Server         : jwzh
Source Server Version : 50538
Source Host           : localhost:3306
Source Database       : source_bj

Target Server Type    : MYSQL
Target Server Version : 50538
File Encoding         : 65001

Date: 2017-03-24 16:33:59
*/

SET FOREIGN_KEY_CHECKS=0;
DROP Database IF EXISTS `source_bj`;
CREATE Database `source_bj`;
use source_bj;
-- ----------------------------
-- Table structure for t_bz_mh_crgxx
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_mh_crgxx`;
CREATE TABLE `t_bz_mh_crgxx` (
  `SYSTEMID` varchar(50) NOT NULL,
  `FILED01` varchar(100) DEFAULT NULL,
  `FILED02` varchar(100) DEFAULT NULL,
  `YXTBH` varchar(100) DEFAULT NULL,
  `BORDER_TYPE` varchar(50) DEFAULT NULL COMMENT '旅客出入境标识',
  `SEG_FLTID` int(11) DEFAULT NULL COMMENT '所属航班序号',
  `FLT_AIRLCODE` varchar(4) DEFAULT NULL COMMENT '航空公司代码',
  `FLT_AIRLCODE_ZW` varchar(255) DEFAULT NULL COMMENT '航空公司',
  `FLT_NUMBER` int(11) DEFAULT NULL COMMENT '航班号',
  `FLIGHT` varchar(255) DEFAULT NULL,
  `FLT_SUFFIX` varchar(3) DEFAULT NULL COMMENT '航班后缀',
  `FLT_DATE` varchar(50) DEFAULT NULL COMMENT '航班日期',
  `SEG_DEPTNO` int(11) DEFAULT NULL COMMENT '起飞航站序号',
  `SEG_DESTNO` int(11) DEFAULT NULL COMMENT '到达航站序号',
  `SEG_DEPT_CODE` varchar(4) DEFAULT NULL COMMENT '起飞航站三字代码',
  `SEG_DEPT_CODE_ZW` varchar(255) DEFAULT NULL COMMENT '起飞航站',
  `SEG_DEST_CODE` varchar(4) DEFAULT NULL COMMENT '到达航站三字代码',
  `SEG_DEST_CODE_ZW` varchar(255) DEFAULT NULL COMMENT '到达航站',
  `STA_DEPTTM` varchar(19) DEFAULT NULL COMMENT '离港时间',
  `STA_ARVETM` varchar(19) DEFAULT NULL COMMENT '进港时间',
  `PDT_DEPT` varchar(4) DEFAULT NULL COMMENT '离港国家二字码',
  `PDT_DEPT_ZW` varchar(255) DEFAULT NULL,
  `PDT_DEST` varchar(4) DEFAULT NULL COMMENT '进港国家二字码',
  `PDT_DEST_ZW` varchar(255) DEFAULT NULL COMMENT '进港国家',
  `PSR_HOSTNBR` int(11) DEFAULT NULL COMMENT '旅客hostnumber',
  `PSR_NAME` varchar(50) DEFAULT NULL COMMENT '旅客姓名（英文）',
  `PSR_CHNNAME` varchar(150) DEFAULT NULL COMMENT '旅客中文姓名',
  `PDT_LASTNAME` varchar(50) DEFAULT NULL,
  `PDT_MIDNAME` varchar(50) DEFAULT NULL COMMENT '旅客中间名',
  `PDT_FIRSTNAME` varchar(50) DEFAULT NULL COMMENT '旅客名',
  `PSR_STATUS` varchar(50) DEFAULT NULL COMMENT '旅客状态',
  `PDT_BIRTHDAY` varchar(10) DEFAULT NULL COMMENT '出生日期',
  `PDT_BIR_ADRESS` varchar(100) DEFAULT NULL COMMENT '出生地',
  `PSR_GENDER` varchar(3) DEFAULT NULL COMMENT '性别',
  `CERT_TYPE` varchar(20) DEFAULT NULL COMMENT '证件类型',
  `CERT_NO` varchar(40) DEFAULT NULL COMMENT '证件号码',
  `PDT_EXPRIRYDATE` varchar(10) DEFAULT NULL COMMENT '过期日期',
  `PDT_ISSUEDATE` varchar(10) DEFAULT NULL COMMENT '发证日期',
  `PDT_ISSUE_COUNTRY` varchar(50) DEFAULT NULL COMMENT '发证国家或城市',
  `PDT_COUNTRY` varchar(4) DEFAULT NULL COMMENT '旅客国家代码',
  `PDT_COUNTRY_ZW` varchar(255) DEFAULT NULL COMMENT '旅客国家',
  `PSR_TYPE` varchar(3) DEFAULT NULL COMMENT '身份类型',
  `PSR_BRDNO` varchar(10) DEFAULT NULL COMMENT '旅客登机号信息',
  `PSR_GROUP` varchar(6) DEFAULT NULL COMMENT '团体旅客标识、团体人数',
  `PSR_ICS` varchar(6) DEFAULT NULL COMMENT 'ics中记录信息',
  `PSR_CRS` varchar(6) DEFAULT NULL COMMENT 'crs中记录信息',
  `PSR_SEATNBR` varchar(50) DEFAULT NULL COMMENT '当前航站的座位号',
  `PSR_FFFR` varchar(22) DEFAULT NULL COMMENT '常旅客/asr旅客信息',
  `PSR_EFMN` varchar(45) DEFAULT NULL COMMENT '电子客票旅客',
  `PSR_BAGS` int(11) DEFAULT NULL COMMENT '行李总件数',
  `PSR_BAGWGT` varchar(10) DEFAULT NULL COMMENT '行李总重量',
  `PSR_CLASS` varchar(10) DEFAULT NULL COMMENT '旅客舱位信息',
  `PSR_CKIPID` varchar(10) DEFAULT NULL COMMENT '执行旅客操作的终端号',
  `PSR_OFFICE` varchar(6) DEFAULT NULL COMMENT '执行值机操作的办公室',
  `PSR_AGENT` varchar(20) DEFAULT NULL COMMENT '执行值机的代理号',
  `PSR_CKITIME` varchar(19) DEFAULT NULL COMMENT '执行值机时间信息',
  `PSR_SIP` varchar(20) DEFAULT NULL COMMENT '共享航班',
  `PSR_FOID_NONET` varchar(22) DEFAULT NULL COMMENT '非et旅客的身份证号',
  `PSR_SEG_SEATNBR` varchar(70) DEFAULT NULL COMMENT '旅客的座位信息',
  `FFQNO` varchar(22) DEFAULT NULL COMMENT '常客号',
  `DATASOURCE` varchar(50) DEFAULT NULL COMMENT '数据来源',
  `TELNO` varchar(100) DEFAULT NULL COMMENT '电话',
  `PAXCLASS` varchar(50) DEFAULT NULL COMMENT '舱位',
  `ADRESS` varchar(100) DEFAULT NULL COMMENT '居住地址',
  `CITY` varchar(100) DEFAULT NULL COMMENT '城市',
  `PROVINCE` varchar(100) DEFAULT NULL COMMENT '省份',
  `ICAO_CODE` varchar(4) DEFAULT NULL COMMENT '国家icao编码',
  `POSTCODE` varchar(100) DEFAULT NULL COMMENT '邮编',
  `EDI` varchar(50) DEFAULT NULL COMMENT '联程旅客标识',
  `ASSBY` varchar(255) DEFAULT NULL,
  `PSR_INF` varchar(50) DEFAULT NULL COMMENT '婴儿标识',
  `PSR_INFNAME` varchar(20) DEFAULT NULL COMMENT '婴儿姓名',
  `STCR` varchar(50) DEFAULT NULL COMMENT '担架旅客标识',
  `WL` varchar(50) DEFAULT NULL COMMENT '轮椅标识',
  `JMP` varchar(50) DEFAULT NULL COMMENT '占用折椅旅客标识',
  `SPECIAL_SEAT` varchar(50) DEFAULT NULL COMMENT '特殊座位标识',
  `SPECIAL_BG` varchar(50) DEFAULT NULL COMMENT '特殊行李标识',
  `SVC` varchar(50) DEFAULT NULL COMMENT '特殊服务',
  `CKI_CHG` varchar(50) DEFAULT NULL COMMENT '值机更改标识',
  `CMT` varchar(50) DEFAULT NULL COMMENT '旅客注释标识',
  `VIP` varchar(50) DEFAULT NULL COMMENT '贵宾旅客标识',
  `URES` varchar(50) DEFAULT NULL COMMENT '未订座旅客标识',
  `PSR_SBYNO` int(11) DEFAULT NULL COMMENT '候补号',
  `PSR_STDRS` varchar(4) DEFAULT NULL,
  `PSR_ACC` varchar(50) DEFAULT NULL COMMENT '值机标识',
  `PSR_SPML_ID` varchar(50) DEFAULT NULL COMMENT '特殊餐食标识',
  `PSR_SPML` varchar(80) DEFAULT NULL COMMENT '特殊餐食',
  `PSR_MSG` varchar(200) DEFAULT NULL COMMENT '旅客信息项',
  `PSR_PSM` varchar(200) DEFAULT NULL COMMENT '旅客服务信息',
  `PSR_PIL` varchar(80) DEFAULT NULL COMMENT '旅客信息清单项',
  `PSR_PCTC` varchar(200) DEFAULT NULL COMMENT '紧急联系信息项',
  `PSR_PSPT` varchar(80) DEFAULT NULL COMMENT '过境信息项',
  `PSR_NOTIFY` varchar(20) DEFAULT NULL COMMENT '广播通知消息',
  `PSR_BLND` varchar(50) DEFAULT NULL COMMENT '盲人旅客标识',
  `PSR_DEAF` varchar(50) DEFAULT NULL COMMENT '耳聋旅客标识',
  `PSR_EMIG` varchar(50) DEFAULT NULL COMMENT '移民旅客',
  `PSR_INAD` varchar(50) DEFAULT NULL COMMENT '不许可旅客',
  `PSR_WTYPE` varchar(4) DEFAULT NULL COMMENT '轮椅类型信息',
  `PSR_WCBD` varchar(80) DEFAULT NULL COMMENT '轮椅-干燥信息项',
  `PSR_WCBW` varchar(80) DEFAULT NULL COMMENT '轮椅-潮湿信息项',
  `PSR_WCMD` varchar(80) DEFAULT NULL COMMENT 'wcmp_item轮椅-手工信息项',
  `PSR_WCOB` varchar(80) DEFAULT NULL COMMENT '轮椅-机上信息项',
  `PSR_CTCA` varchar(80) DEFAULT NULL COMMENT 'ctca_item(代理人联系信息）',
  `PSR_RUSH` varchar(80) DEFAULT NULL COMMENT '速运行李标识',
  `PSR_HBPRBG` varchar(20) DEFAULT NULL COMMENT 'hbpr指令中行李带信息',
  `PSR_AVIH` varchar(50) DEFAULT NULL COMMENT '手提狗笼标识',
  `PSR_PETC` varchar(50) DEFAULT NULL COMMENT '宠物笼子标识',
  `PSR_BAGGAGE` varchar(30) DEFAULT NULL COMMENT '行李',
  `PSR_UNATTACH` varchar(50) DEFAULT NULL COMMENT '不跟人行李标识信息',
  `PSR_ARST` varchar(10) DEFAULT NULL COMMENT '分配/预留座位类型',
  `PSR_XASR` varchar(50) DEFAULT NULL COMMENT '取消asr旅客标识',
  `PSR_XABP` varchar(50) DEFAULT NULL COMMENT '取消abp旅客标识',
  `PSR_EXSTSEAT` varchar(8) DEFAULT NULL COMMENT '额外占座',
  `PSR_RST` varchar(5) DEFAULT NULL COMMENT '预留座位种类信息',
  `PSR_SPE` varchar(6) DEFAULT NULL COMMENT '座位个人喜好项',
  `PSR_ASOBOI` varchar(50) DEFAULT NULL COMMENT '被他人占用的座位标识信息',
  `PSR_OSR` varchar(10) DEFAULT NULL COMMENT '最初预定+d163座位项',
  `PSR_AEC` varchar(50) DEFAULT NULL COMMENT 'aec旅客标识',
  `PSR_SEA` varchar(50) DEFAULT NULL COMMENT '给aec旅客重新分配座位标识',
  `PSR_REA` varchar(50) DEFAULT NULL COMMENT '给aec旅客重新订座标识',
  `PSR_BSCT` varchar(50) DEFAULT NULL COMMENT '摇篮类型',
  `PSR_UDGRADE` varchar(20) DEFAULT NULL COMMENT '升降舱类型',
  `PSR_OFL` varchar(50) DEFAULT NULL COMMENT '被拉下旅客表示信息',
  `PSR_DEP` varchar(50) DEFAULT NULL COMMENT '拉下类型标识',
  `PSR_RTFI` varchar(20) DEFAULT NULL COMMENT '再值机到某航班信息',
  `PSR_RFFI` varchar(20) DEFAULT NULL COMMENT '从某航班再值机信息',
  `PSR_TSI` varchar(20) DEFAULT NULL COMMENT '旅行状态标识',
  `PSR_XRES` varchar(50) DEFAULT NULL COMMENT '取消订座标识',
  `PSR_XT` varchar(50) DEFAULT NULL COMMENT '取消转港标识信息',
  `PSR_CITYCANC` varchar(50) DEFAULT NULL COMMENT '城市取消标识',
  `PSR_VUDGRADE` varchar(50) DEFAULT NULL COMMENT '自愿升降舱标识',
  `PSR_EDI_WARN` varchar(80) DEFAULT NULL COMMENT 'edifact警告项',
  `PSR_INBOUND` varchar(40) DEFAULT NULL COMMENT '入港',
  `PSR_EDII` varchar(50) DEFAULT NULL COMMENT '进港联乘edi旅客标识',
  `PSR_OUTBOUND` varchar(200) DEFAULT NULL COMMENT '出港',
  `PSR_EDIO` varchar(50) DEFAULT NULL COMMENT '出港联乘edi旅客标识',
  `PSR_EDI_DEPT` varchar(3) DEFAULT NULL COMMENT 'edi旅客始发站',
  `PSR_EDI_DEPT_ZW` varchar(255) DEFAULT NULL COMMENT 'edi旅客始发站',
  `PSR_EDI_DEST` varchar(3) DEFAULT NULL COMMENT 'edi旅客到达站',
  `PSR_EDI_DEST_ZW` varchar(255) DEFAULT NULL COMMENT 'edi旅客到达站',
  `PNR_REF` varchar(6) DEFAULT NULL COMMENT 'icspnr记录编号',
  `DELETE_FLAG` varchar(50) DEFAULT NULL COMMENT '删除标志',
  `DELETE_FLT_ID` varchar(20) DEFAULT NULL COMMENT '删除航班id',
  `PSR_ARRIVE_TIME` varchar(19) DEFAULT NULL COMMENT '入库时间',
  `FILENAME` varchar(50) DEFAULT NULL COMMENT '原始数据包的文件名',
  `FILE_TIME` varchar(50) DEFAULT NULL COMMENT '文件时间',
  `CT_DT` varchar(19) DEFAULT NULL COMMENT '导入数据时间',
  `BZK_RKSJ` datetime DEFAULT NULL,
  `BZK_GXSJ` datetime DEFAULT NULL,
  `BZK_ZZJG` varchar(255) DEFAULT NULL,
  `BZK_SCBZ` varchar(255) DEFAULT NULL,
  `ZYK_SSXTMC` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_mh_crgxx_dz
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_mh_crgxx_dz`;
CREATE TABLE `t_bz_mh_crgxx_dz` (
  `SYSTEMID` varchar(100) NOT NULL,
  `YXTBH` varchar(255) DEFAULT NULL,
  `PNR_REF` varchar(8) DEFAULT NULL COMMENT 'icspnr记录编号',
  `PNR_CR_DT` varchar(8) DEFAULT NULL COMMENT 'pnr创建日期',
  `AIR_CARR_CD` varchar(2) DEFAULT NULL COMMENT '承运航空公司代码',
  `AIR_SEG_FLT_NBR_SFX` varchar(4) DEFAULT NULL COMMENT '航班号后缀',
  `AIR_SEG_FLT_NBR` varchar(8) DEFAULT NULL COMMENT '航班号',
  `FLIGHT` varchar(255) DEFAULT NULL,
  `AIR_SEG_DPT_DT_LCL` varchar(8) DEFAULT NULL COMMENT '当地出发日期',
  `AIR_SEG_DPT_TM_LCL` varchar(8) DEFAULT NULL COMMENT '当地出发时间',
  `AIR_SEG_ARRV_TM_LCL` varchar(8) DEFAULT NULL COMMENT '当地到达时间',
  `AIR_SEG_ARRV_DT_LCL` int(11) DEFAULT NULL COMMENT '当地到达日期',
  `AIR_SEG_DPT_AIRPT_CD` varchar(3) DEFAULT NULL COMMENT '登机机场代码',
  `AIR_SEG_DPT_AIRPT_CD_ZW` varchar(255) DEFAULT NULL COMMENT '登机机场',
  `AIR_SEG_ARRV_AIRPT_CD` varchar(3) DEFAULT NULL COMMENT '到达机场代码',
  `AIR_SEG_ARRV_AIRPT_CD_ZW` varchar(255) DEFAULT NULL COMMENT '到达机场',
  `SUB_CLS_CD` varchar(50) DEFAULT NULL COMMENT '子舱位',
  `OFFC_CD` varchar(10) DEFAULT NULL COMMENT '代理人代号',
  `OFFC_CD_ZW` varchar(255) DEFAULT NULL COMMENT '代理人',
  `OPR_STAT_CD` varchar(2) DEFAULT NULL COMMENT '行动代码',
  `OPR_STAT_CD_ZW` varchar(255) DEFAULT NULL COMMENT '行动',
  `RSP_AIRLN_CD` varchar(2) DEFAULT NULL COMMENT '责任航空公司',
  `RSP_AIRLN_CD_ZW` varchar(255) DEFAULT NULL COMMENT '责任航空公司',
  `RSP_OFC_CD` varchar(6) DEFAULT NULL COMMENT '责任代理人',
  `RSP_OFC_CD_ZW` varchar(255) DEFAULT NULL COMMENT '责任代理人',
  `PAS_ID` varchar(3) DEFAULT NULL COMMENT 'pnr旅客编号',
  `PAS_LST_NM` varchar(40) DEFAULT NULL COMMENT '旅客姓',
  `PAS_FST_NM` varchar(40) DEFAULT NULL COMMENT '旅客名',
  `PAS_CHN_NM` varchar(100) DEFAULT NULL COMMENT '旅客中文名',
  `PAS_ID_TYPE` varchar(5) DEFAULT NULL COMMENT '旅客证件类型',
  `PAS_ID_NBR` varchar(50) DEFAULT NULL COMMENT '旅客证件号码',
  `FFP_ID_NBR` varchar(20) DEFAULT NULL COMMENT '常旅客编号',
  `GRP_IND` varchar(50) DEFAULT NULL COMMENT '团队标识',
  `GRP_NM` varchar(50) DEFAULT NULL COMMENT '团队名称',
  `VIP_IND` varchar(50) DEFAULT NULL COMMENT 'vip标识',
  `PN_SEAT` varchar(3) DEFAULT NULL COMMENT 'pnr总人数与该旅客一起定票的人数',
  `OPERATEDATE` varchar(8) DEFAULT NULL COMMENT '操作日期',
  `OPERATETIME` varchar(8) DEFAULT NULL COMMENT '操作时间',
  `FILENAME` varchar(50) DEFAULT NULL COMMENT '原始数据包的文件名',
  `CT_DT` varchar(19) DEFAULT NULL COMMENT '导入数据的时间',
  `BZK_RKSJ` datetime DEFAULT NULL,
  `BZK_GXSJ` datetime DEFAULT NULL,
  `BZK_ZZJG` varchar(255) DEFAULT NULL,
  `BZK_SCBZ` varchar(255) DEFAULT NULL,
  `ZYK_SSXTMC` varchar(255) DEFAULT NULL,
  `OFFDAY_DEPTTM` varchar(255) DEFAULT NULL,
  `OFFDAY_ARVETM` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_mh_lgxx_dz_ls
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_mh_lgxx_dz_ls`;
CREATE TABLE `t_bz_mh_lgxx_dz_ls` (
  `SYSTEMID` varchar(100) NOT NULL,
  `YXTBH` varchar(255) DEFAULT NULL,
  `PNR_REF` varchar(8) DEFAULT NULL COMMENT 'icspnr记录编号',
  `PNR_CR_DT` varchar(8) DEFAULT NULL COMMENT 'pnr创建日期',
  `AIR_CARR_CD` varchar(2) DEFAULT NULL COMMENT '承运航空公司代码',
  `AIR_SEG_FLT_NBR_SFX` varchar(4) DEFAULT NULL COMMENT '航班号后缀',
  `AIR_SEG_FLT_NBR` varchar(8) DEFAULT NULL COMMENT '航班号',
  `FLIGHT` varchar(255) DEFAULT NULL,
  `AIR_SEG_DPT_DT_LCL` varchar(8) DEFAULT NULL COMMENT '当地出发日期',
  `AIR_SEG_DPT_TM_LCL` varchar(8) DEFAULT NULL COMMENT '当地出发时间',
  `AIR_SEG_ARRV_TM_LCL` varchar(8) DEFAULT NULL COMMENT '当地到达时间',
  `AIR_SEG_ARRV_DT_LCL` int(11) DEFAULT NULL COMMENT '当地到达日期',
  `AIR_SEG_DPT_AIRPT_CD` varchar(3) DEFAULT NULL COMMENT '登机机场代码',
  `AIR_SEG_DPT_AIRPT_CD_ZW` varchar(255) DEFAULT NULL COMMENT '登机机场',
  `AIR_SEG_ARRV_AIRPT_CD` varchar(3) DEFAULT NULL COMMENT '到达机场代码',
  `AIR_SEG_ARRV_AIRPT_CD_ZW` varchar(255) DEFAULT NULL COMMENT '到达机场',
  `SUB_CLS_CD` varchar(50) DEFAULT NULL COMMENT '子舱位',
  `OFFC_CD` varchar(10) DEFAULT NULL COMMENT '代理人代号',
  `OFFC_CD_ZW` varchar(255) DEFAULT NULL COMMENT '代理人',
  `OPR_STAT_CD` varchar(2) DEFAULT NULL COMMENT '行动代码',
  `OPR_STAT_CD_ZW` varchar(255) DEFAULT NULL COMMENT '行动',
  `RSP_AIRLN_CD` varchar(2) DEFAULT NULL COMMENT '责任航空公司',
  `RSP_AIRLN_CD_ZW` varchar(255) DEFAULT NULL COMMENT '责任航空公司',
  `RSP_OFC_CD` varchar(6) DEFAULT NULL COMMENT '责任代理人',
  `RSP_OFC_CD_ZW` varchar(255) DEFAULT NULL COMMENT '责任代理人',
  `PAS_ID` varchar(3) DEFAULT NULL COMMENT 'pnr旅客编号',
  `PAS_LST_NM` varchar(40) DEFAULT NULL COMMENT '旅客姓',
  `PAS_FST_NM` varchar(40) DEFAULT NULL COMMENT '旅客名',
  `PAS_CHN_NM` varchar(100) DEFAULT NULL COMMENT '旅客中文名',
  `PAS_ID_TYPE` varchar(5) DEFAULT NULL COMMENT '旅客证件类型',
  `PAS_ID_NBR` varchar(50) DEFAULT NULL COMMENT '旅客证件号码',
  `FFP_ID_NBR` varchar(20) DEFAULT NULL COMMENT '常旅客编号',
  `GRP_IND` varchar(50) DEFAULT NULL COMMENT '团队标识',
  `GRP_NM` varchar(50) DEFAULT NULL COMMENT '团队名称',
  `VIP_IND` varchar(50) DEFAULT NULL COMMENT 'vip标识',
  `PN_SEAT` varchar(3) DEFAULT NULL COMMENT 'pnr总人数与该旅客一起定票的人数',
  `OPERATEDATE` varchar(8) DEFAULT NULL COMMENT '操作日期',
  `OPERATETIME` varchar(8) DEFAULT NULL COMMENT '操作时间',
  `FILENAME` varchar(50) DEFAULT NULL COMMENT '原始数据包的文件名',
  `CT_DT` varchar(19) DEFAULT NULL COMMENT '导入数据的时间',
  `BZK_RKSJ` datetime DEFAULT NULL,
  `BZK_GXSJ` datetime DEFAULT NULL,
  `BZK_ZZJG` varchar(255) DEFAULT NULL,
  `BZK_SCBZ` varchar(255) DEFAULT NULL,
  `ZYK_SSXTMC` varchar(255) DEFAULT NULL,
  `OFFDAY_DEPTTM` varchar(255) DEFAULT NULL,
  `OFFDAY_ARVETM` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_mh_lgxx_ls
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_mh_lgxx_ls`;
CREATE TABLE `t_bz_mh_lgxx_ls` (
  `SYSTEMID` varchar(50) NOT NULL,
  `FILED01` varchar(100) DEFAULT NULL,
  `FILED02` varchar(100) DEFAULT NULL,
  `YXTBH` varchar(100) DEFAULT NULL,
  `BORDER_TYPE` varchar(50) DEFAULT NULL COMMENT '旅客出入境标识',
  `SEG_FLTID` int(11) DEFAULT NULL COMMENT '所属航班序号',
  `FLT_AIRLCODE` varchar(4) DEFAULT NULL COMMENT '航空公司代码',
  `FLT_AIRLCODE_ZW` varchar(255) DEFAULT NULL COMMENT '航空公司',
  `FLT_NUMBER` int(11) DEFAULT NULL COMMENT '航班号',
  `FLIGHT` varchar(255) DEFAULT NULL,
  `FLT_SUFFIX` varchar(3) DEFAULT NULL COMMENT '航班后缀',
  `FLT_DATE` varchar(50) DEFAULT NULL COMMENT '航班日期',
  `SEG_DEPTNO` int(11) DEFAULT NULL COMMENT '起飞航站序号',
  `SEG_DESTNO` int(11) DEFAULT NULL COMMENT '到达航站序号',
  `SEG_DEPT_CODE` varchar(4) DEFAULT NULL COMMENT '起飞航站三字代码',
  `SEG_DEPT_CODE_ZW` varchar(255) DEFAULT NULL COMMENT '起飞航站',
  `SEG_DEST_CODE` varchar(4) DEFAULT NULL COMMENT '到达航站三字代码',
  `SEG_DEST_CODE_ZW` varchar(255) DEFAULT NULL COMMENT '到达航站',
  `STA_DEPTTM` varchar(19) DEFAULT NULL COMMENT '离港时间',
  `STA_ARVETM` varchar(19) DEFAULT NULL COMMENT '进港时间',
  `PDT_DEPT` varchar(4) DEFAULT NULL COMMENT '离港国家二字码',
  `PDT_DEPT_ZW` varchar(255) DEFAULT NULL,
  `PDT_DEST` varchar(4) DEFAULT NULL COMMENT '进港国家二字码',
  `PDT_DEST_ZW` varchar(255) DEFAULT NULL COMMENT '进港国家',
  `PSR_HOSTNBR` int(11) DEFAULT NULL COMMENT '旅客hostnumber',
  `PSR_NAME` varchar(50) DEFAULT NULL COMMENT '旅客姓名（英文）',
  `PSR_CHNNAME` varchar(150) DEFAULT NULL COMMENT '旅客中文姓名',
  `PDT_LASTNAME` varchar(50) DEFAULT NULL,
  `PDT_MIDNAME` varchar(50) DEFAULT NULL COMMENT '旅客中间名',
  `PDT_FIRSTNAME` varchar(50) DEFAULT NULL COMMENT '旅客名',
  `PSR_STATUS` varchar(2) DEFAULT NULL COMMENT '旅客状态',
  `PDT_BIRTHDAY` varchar(10) DEFAULT NULL COMMENT '出生日期',
  `PDT_BIR_ADRESS` varchar(100) DEFAULT NULL COMMENT '出生地',
  `PSR_GENDER` varchar(3) DEFAULT NULL COMMENT '性别',
  `CERT_TYPE` varchar(20) DEFAULT NULL COMMENT '证件类型',
  `CERT_NO` varchar(40) DEFAULT NULL COMMENT '证件号码',
  `PDT_EXPRIRYDATE` varchar(10) DEFAULT NULL COMMENT '过期日期',
  `PDT_ISSUEDATE` varchar(10) DEFAULT NULL COMMENT '发证日期',
  `PDT_ISSUE_COUNTRY` varchar(50) DEFAULT NULL COMMENT '发证国家或城市',
  `PDT_COUNTRY` varchar(4) DEFAULT NULL COMMENT '旅客国家代码',
  `PDT_COUNTRY_ZW` varchar(255) DEFAULT NULL COMMENT '旅客国家',
  `PSR_TYPE` varchar(3) DEFAULT NULL COMMENT '身份类型',
  `PSR_BRDNO` varchar(10) DEFAULT NULL COMMENT '旅客登机号信息',
  `PSR_GROUP` varchar(6) DEFAULT NULL COMMENT '团体旅客标识、团体人数',
  `PSR_ICS` varchar(6) DEFAULT NULL COMMENT 'ics中记录信息',
  `PSR_CRS` varchar(6) DEFAULT NULL COMMENT 'crs中记录信息',
  `PSR_SEATNBR` varchar(50) DEFAULT NULL COMMENT '当前航站的座位号',
  `PSR_FFFR` varchar(22) DEFAULT NULL COMMENT '常旅客/asr旅客信息',
  `PSR_EFMN` varchar(45) DEFAULT NULL COMMENT '电子客票旅客',
  `PSR_BAGS` int(11) DEFAULT NULL COMMENT '行李总件数',
  `PSR_BAGWGT` varchar(10) DEFAULT NULL COMMENT '行李总重量',
  `PSR_CLASS` varchar(10) DEFAULT NULL COMMENT '旅客舱位信息',
  `PSR_CKIPID` varchar(10) DEFAULT NULL COMMENT '执行旅客操作的终端号',
  `PSR_OFFICE` varchar(6) DEFAULT NULL COMMENT '执行值机操作的办公室',
  `PSR_AGENT` varchar(20) DEFAULT NULL COMMENT '执行值机的代理号',
  `PSR_CKITIME` varchar(19) DEFAULT NULL COMMENT '执行值机时间信息',
  `PSR_SIP` varchar(20) DEFAULT NULL COMMENT '共享航班',
  `PSR_FOID_NONET` varchar(22) DEFAULT NULL COMMENT '非et旅客的身份证号',
  `PSR_SEG_SEATNBR` varchar(70) DEFAULT NULL COMMENT '旅客的座位信息',
  `FFQNO` varchar(22) DEFAULT NULL COMMENT '常客号',
  `DATASOURCE` varchar(50) DEFAULT NULL COMMENT '数据来源',
  `TELNO` varchar(100) DEFAULT NULL COMMENT '电话',
  `PAXCLASS` varchar(50) DEFAULT NULL COMMENT '舱位',
  `ADRESS` varchar(100) DEFAULT NULL COMMENT '居住地址',
  `CITY` varchar(100) DEFAULT NULL COMMENT '城市',
  `PROVINCE` varchar(100) DEFAULT NULL COMMENT '省份',
  `ICAO_CODE` varchar(4) DEFAULT NULL COMMENT '国家icao编码',
  `POSTCODE` varchar(100) DEFAULT NULL COMMENT '邮编',
  `EDI` varchar(50) DEFAULT NULL COMMENT '联程旅客标识',
  `ASSBY` varchar(255) DEFAULT NULL,
  `PSR_INF` varchar(50) DEFAULT NULL COMMENT '婴儿标识',
  `PSR_INFNAME` varchar(20) DEFAULT NULL COMMENT '婴儿姓名',
  `STCR` varchar(50) DEFAULT NULL COMMENT '担架旅客标识',
  `WL` varchar(50) DEFAULT NULL COMMENT '轮椅标识',
  `JMP` varchar(50) DEFAULT NULL COMMENT '占用折椅旅客标识',
  `SPECIAL_SEAT` varchar(50) DEFAULT NULL COMMENT '特殊座位标识',
  `SPECIAL_BG` varchar(50) DEFAULT NULL COMMENT '特殊行李标识',
  `SVC` varchar(50) DEFAULT NULL COMMENT '特殊服务',
  `CKI_CHG` varchar(50) DEFAULT NULL COMMENT '值机更改标识',
  `CMT` varchar(50) DEFAULT NULL COMMENT '旅客注释标识',
  `VIP` varchar(50) DEFAULT NULL COMMENT '贵宾旅客标识',
  `URES` varchar(50) DEFAULT NULL COMMENT '未订座旅客标识',
  `PSR_SBYNO` int(11) DEFAULT NULL COMMENT '候补号',
  `PSR_STDRS` varchar(4) DEFAULT NULL,
  `PSR_ACC` varchar(50) DEFAULT NULL COMMENT '值机标识',
  `PSR_SPML_ID` varchar(50) DEFAULT NULL COMMENT '特殊餐食标识',
  `PSR_SPML` varchar(80) DEFAULT NULL COMMENT '特殊餐食',
  `PSR_MSG` varchar(200) DEFAULT NULL COMMENT '旅客信息项',
  `PSR_PSM` varchar(200) DEFAULT NULL COMMENT '旅客服务信息',
  `PSR_PIL` varchar(80) DEFAULT NULL COMMENT '旅客信息清单项',
  `PSR_PCTC` varchar(200) DEFAULT NULL COMMENT '紧急联系信息项',
  `PSR_PSPT` varchar(80) DEFAULT NULL COMMENT '过境信息项',
  `PSR_NOTIFY` varchar(20) DEFAULT NULL COMMENT '广播通知消息',
  `PSR_BLND` varchar(50) DEFAULT NULL COMMENT '盲人旅客标识',
  `PSR_DEAF` varchar(50) DEFAULT NULL COMMENT '耳聋旅客标识',
  `PSR_EMIG` varchar(50) DEFAULT NULL COMMENT '移民旅客',
  `PSR_INAD` varchar(50) DEFAULT NULL COMMENT '不许可旅客',
  `PSR_WTYPE` varchar(4) DEFAULT NULL COMMENT '轮椅类型信息',
  `PSR_WCBD` varchar(80) DEFAULT NULL COMMENT '轮椅-干燥信息项',
  `PSR_WCBW` varchar(80) DEFAULT NULL COMMENT '轮椅-潮湿信息项',
  `PSR_WCMD` varchar(80) DEFAULT NULL COMMENT 'wcmp_item轮椅-手工信息项',
  `PSR_WCOB` varchar(80) DEFAULT NULL COMMENT '轮椅-机上信息项',
  `PSR_CTCA` varchar(80) DEFAULT NULL COMMENT 'ctca_item(代理人联系信息）',
  `PSR_RUSH` varchar(80) DEFAULT NULL COMMENT '速运行李标识',
  `PSR_HBPRBG` varchar(20) DEFAULT NULL COMMENT 'hbpr指令中行李带信息',
  `PSR_AVIH` varchar(50) DEFAULT NULL COMMENT '手提狗笼标识',
  `PSR_PETC` varchar(50) DEFAULT NULL COMMENT '宠物笼子标识',
  `PSR_BAGGAGE` varchar(30) DEFAULT NULL COMMENT '行李',
  `PSR_UNATTACH` varchar(50) DEFAULT NULL COMMENT '不跟人行李标识信息',
  `PSR_ARST` varchar(10) DEFAULT NULL COMMENT '分配/预留座位类型',
  `PSR_XASR` varchar(50) DEFAULT NULL COMMENT '取消asr旅客标识',
  `PSR_XABP` varchar(50) DEFAULT NULL COMMENT '取消abp旅客标识',
  `PSR_EXSTSEAT` varchar(8) DEFAULT NULL COMMENT '额外占座',
  `PSR_RST` varchar(5) DEFAULT NULL COMMENT '预留座位种类信息',
  `PSR_SPE` varchar(6) DEFAULT NULL COMMENT '座位个人喜好项',
  `PSR_ASOBOI` varchar(50) DEFAULT NULL COMMENT '被他人占用的座位标识信息',
  `PSR_OSR` varchar(10) DEFAULT NULL COMMENT '最初预定+d163座位项',
  `PSR_AEC` varchar(50) DEFAULT NULL COMMENT 'aec旅客标识',
  `PSR_SEA` varchar(50) DEFAULT NULL COMMENT '给aec旅客重新分配座位标识',
  `PSR_REA` varchar(50) DEFAULT NULL COMMENT '给aec旅客重新订座标识',
  `PSR_BSCT` varchar(50) DEFAULT NULL COMMENT '摇篮类型',
  `PSR_UDGRADE` varchar(20) DEFAULT NULL COMMENT '升降舱类型',
  `PSR_OFL` varchar(50) DEFAULT NULL COMMENT '被拉下旅客表示信息',
  `PSR_DEP` varchar(50) DEFAULT NULL COMMENT '拉下类型标识',
  `PSR_RTFI` varchar(20) DEFAULT NULL COMMENT '再值机到某航班信息',
  `PSR_RFFI` varchar(20) DEFAULT NULL COMMENT '从某航班再值机信息',
  `PSR_TSI` varchar(20) DEFAULT NULL COMMENT '旅行状态标识',
  `PSR_XRES` varchar(50) DEFAULT NULL COMMENT '取消订座标识',
  `PSR_XT` varchar(50) DEFAULT NULL COMMENT '取消转港标识信息',
  `PSR_CITYCANC` varchar(50) DEFAULT NULL COMMENT '城市取消标识',
  `PSR_VUDGRADE` varchar(50) DEFAULT NULL COMMENT '自愿升降舱标识',
  `PSR_EDI_WARN` varchar(80) DEFAULT NULL COMMENT 'edifact警告项',
  `PSR_INBOUND` varchar(40) DEFAULT NULL COMMENT '入港',
  `PSR_EDII` varchar(50) DEFAULT NULL COMMENT '进港联乘edi旅客标识',
  `PSR_OUTBOUND` varchar(200) DEFAULT NULL COMMENT '出港',
  `PSR_EDIO` varchar(50) DEFAULT NULL COMMENT '出港联乘edi旅客标识',
  `PSR_EDI_DEPT` varchar(3) DEFAULT NULL COMMENT 'edi旅客始发站',
  `PSR_EDI_DEPT_ZW` varchar(255) DEFAULT NULL COMMENT 'edi旅客始发站',
  `PSR_EDI_DEST` varchar(3) DEFAULT NULL COMMENT 'edi旅客到达站',
  `PSR_EDI_DEST_ZW` varchar(255) DEFAULT NULL COMMENT 'edi旅客到达站',
  `PNR_REF` varchar(6) DEFAULT NULL COMMENT 'icspnr记录编号',
  `DELETE_FLAG` varchar(50) DEFAULT NULL COMMENT '删除标志',
  `DELETE_FLT_ID` varchar(20) DEFAULT NULL COMMENT '删除航班id',
  `PSR_ARRIVE_TIME` varchar(19) DEFAULT NULL COMMENT '入库时间',
  `FILENAME` varchar(50) DEFAULT NULL COMMENT '原始数据包的文件名',
  `FILE_TIME` varchar(15) DEFAULT NULL COMMENT '文件时间',
  `CT_DT` varchar(19) DEFAULT NULL COMMENT '导入数据时间',
  `BZK_RKSJ` datetime DEFAULT NULL,
  `BZK_GXSJ` datetime DEFAULT NULL,
  `BZK_ZZJG` varchar(255) DEFAULT NULL,
  `BZK_SCBZ` varchar(255) DEFAULT NULL,
  `ZYK_SSXTMC` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_mh_rgxx_dz_ls
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_mh_rgxx_dz_ls`;
CREATE TABLE `t_bz_mh_rgxx_dz_ls` (
  `SYSTEMID` varchar(100) NOT NULL,
  `YXTBH` varchar(255) DEFAULT NULL,
  `PNR_REF` varchar(8) DEFAULT NULL COMMENT 'icspnr记录编号',
  `PNR_CR_DT` varchar(8) DEFAULT NULL COMMENT 'pnr创建日期',
  `AIR_CARR_CD` varchar(2) DEFAULT NULL COMMENT '承运航空公司代码',
  `AIR_SEG_FLT_NBR_SFX` varchar(4) DEFAULT NULL COMMENT '航班号后缀',
  `AIR_SEG_FLT_NBR` varchar(8) DEFAULT NULL COMMENT '航班号',
  `FLIGHT` varchar(255) DEFAULT NULL,
  `AIR_SEG_DPT_DT_LCL` varchar(8) DEFAULT NULL COMMENT '当地出发日期',
  `AIR_SEG_DPT_TM_LCL` varchar(8) DEFAULT NULL COMMENT '当地出发时间',
  `AIR_SEG_ARRV_TM_LCL` varchar(8) DEFAULT NULL COMMENT '当地到达时间',
  `AIR_SEG_ARRV_DT_LCL` int(11) DEFAULT NULL COMMENT '当地到达日期',
  `AIR_SEG_DPT_AIRPT_CD` varchar(3) DEFAULT NULL COMMENT '登机机场代码',
  `AIR_SEG_DPT_AIRPT_CD_ZW` varchar(255) DEFAULT NULL COMMENT '登机机场',
  `AIR_SEG_ARRV_AIRPT_CD` varchar(3) DEFAULT NULL COMMENT '到达机场代码',
  `AIR_SEG_ARRV_AIRPT_CD_ZW` varchar(255) DEFAULT NULL COMMENT '到达机场',
  `SUB_CLS_CD` varchar(1) DEFAULT NULL COMMENT '子舱位',
  `OFFC_CD` varchar(10) DEFAULT NULL COMMENT '代理人代号',
  `OFFC_CD_ZW` varchar(255) DEFAULT NULL COMMENT '代理人',
  `OPR_STAT_CD` varchar(2) DEFAULT NULL COMMENT '行动代码',
  `OPR_STAT_CD_ZW` varchar(255) DEFAULT NULL COMMENT '行动',
  `RSP_AIRLN_CD` varchar(2) DEFAULT NULL COMMENT '责任航空公司',
  `RSP_AIRLN_CD_ZW` varchar(255) DEFAULT NULL COMMENT '责任航空公司',
  `RSP_OFC_CD` varchar(6) DEFAULT NULL COMMENT '责任代理人',
  `RSP_OFC_CD_ZW` varchar(255) DEFAULT NULL COMMENT '责任代理人',
  `PAS_ID` varchar(3) DEFAULT NULL COMMENT 'pnr旅客编号',
  `PAS_LST_NM` varchar(40) DEFAULT NULL COMMENT '旅客姓',
  `PAS_FST_NM` varchar(40) DEFAULT NULL COMMENT '旅客名',
  `PAS_CHN_NM` varchar(100) DEFAULT NULL COMMENT '旅客中文名',
  `PAS_ID_TYPE` varchar(5) DEFAULT NULL COMMENT '旅客证件类型',
  `PAS_ID_NBR` varchar(50) DEFAULT NULL COMMENT '旅客证件号码',
  `FFP_ID_NBR` varchar(20) DEFAULT NULL COMMENT '常旅客编号',
  `GRP_IND` varchar(1) DEFAULT NULL COMMENT '团队标识',
  `GRP_NM` varchar(50) DEFAULT NULL COMMENT '团队名称',
  `VIP_IND` varchar(1) DEFAULT NULL COMMENT 'vip标识',
  `PN_SEAT` varchar(3) DEFAULT NULL COMMENT 'pnr总人数与该旅客一起定票的人数',
  `OPERATEDATE` varchar(8) DEFAULT NULL COMMENT '操作日期',
  `OPERATETIME` varchar(8) DEFAULT NULL COMMENT '操作时间',
  `FILENAME` varchar(50) DEFAULT NULL COMMENT '原始数据包的文件名',
  `CT_DT` varchar(19) DEFAULT NULL COMMENT '导入数据的时间',
  `BZK_RKSJ` datetime DEFAULT NULL,
  `BZK_GXSJ` datetime DEFAULT NULL,
  `BZK_ZZJG` varchar(255) DEFAULT NULL,
  `BZK_SCBZ` varchar(255) DEFAULT NULL,
  `ZYK_SSXTMC` varchar(255) DEFAULT NULL,
  `OFFDAY_DEPTTM` varchar(255) DEFAULT NULL,
  `OFFDAY_ARVETM` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_mh_rgxx_ls
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_mh_rgxx_ls`;
CREATE TABLE `t_bz_mh_rgxx_ls` (
  `SYSTEMID` varchar(50) NOT NULL,
  `FILED01` varchar(100) DEFAULT NULL,
  `FILED02` varchar(100) DEFAULT NULL,
  `YXTBH` varchar(100) DEFAULT NULL,
  `BORDER_TYPE` varchar(50) DEFAULT NULL COMMENT '旅客出入境标识',
  `SEG_FLTID` int(11) DEFAULT NULL COMMENT '所属航班序号',
  `FLT_AIRLCODE` varchar(4) DEFAULT NULL COMMENT '航空公司代码',
  `FLT_AIRLCODE_ZW` varchar(255) DEFAULT NULL COMMENT '航空公司',
  `FLT_NUMBER` int(11) DEFAULT NULL COMMENT '航班号',
  `FLIGHT` varchar(255) DEFAULT NULL,
  `FLT_SUFFIX` varchar(3) DEFAULT NULL COMMENT '航班后缀',
  `FLT_DATE` varchar(50) DEFAULT NULL COMMENT '航班日期',
  `SEG_DEPTNO` int(11) DEFAULT NULL COMMENT '起飞航站序号',
  `SEG_DESTNO` int(11) DEFAULT NULL COMMENT '到达航站序号',
  `SEG_DEPT_CODE` varchar(4) DEFAULT NULL COMMENT '起飞航站三字代码',
  `SEG_DEPT_CODE_ZW` varchar(255) DEFAULT NULL COMMENT '起飞航站',
  `SEG_DEST_CODE` varchar(4) DEFAULT NULL COMMENT '到达航站三字代码',
  `SEG_DEST_CODE_ZW` varchar(255) DEFAULT NULL COMMENT '到达航站',
  `STA_DEPTTM` varchar(19) DEFAULT NULL COMMENT '离港时间',
  `STA_ARVETM` varchar(19) DEFAULT NULL COMMENT '进港时间',
  `PDT_DEPT` varchar(4) DEFAULT NULL COMMENT '离港国家二字码',
  `PDT_DEPT_ZW` varchar(255) DEFAULT NULL,
  `PDT_DEST` varchar(4) DEFAULT NULL COMMENT '进港国家二字码',
  `PDT_DEST_ZW` varchar(255) DEFAULT NULL COMMENT '进港国家',
  `PSR_HOSTNBR` int(11) DEFAULT NULL COMMENT '旅客hostnumber',
  `PSR_NAME` varchar(50) DEFAULT NULL COMMENT '旅客姓名（英文）',
  `PSR_CHNNAME` varchar(150) DEFAULT NULL COMMENT '旅客中文姓名',
  `PDT_LASTNAME` varchar(50) DEFAULT NULL,
  `PDT_MIDNAME` varchar(50) DEFAULT NULL COMMENT '旅客中间名',
  `PDT_FIRSTNAME` varchar(50) DEFAULT NULL COMMENT '旅客名',
  `PSR_STATUS` varchar(2) DEFAULT NULL COMMENT '旅客状态',
  `PDT_BIRTHDAY` varchar(10) DEFAULT NULL COMMENT '出生日期',
  `PDT_BIR_ADRESS` varchar(100) DEFAULT NULL COMMENT '出生地',
  `PSR_GENDER` varchar(3) DEFAULT NULL COMMENT '性别',
  `CERT_TYPE` varchar(20) DEFAULT NULL COMMENT '证件类型',
  `CERT_NO` varchar(40) DEFAULT NULL COMMENT '证件号码',
  `PDT_EXPRIRYDATE` varchar(10) DEFAULT NULL COMMENT '过期日期',
  `PDT_ISSUEDATE` varchar(10) DEFAULT NULL COMMENT '发证日期',
  `PDT_ISSUE_COUNTRY` varchar(50) DEFAULT NULL COMMENT '发证国家或城市',
  `PDT_COUNTRY` varchar(4) DEFAULT NULL COMMENT '旅客国家代码',
  `PDT_COUNTRY_ZW` varchar(255) DEFAULT NULL COMMENT '旅客国家',
  `PSR_TYPE` varchar(3) DEFAULT NULL COMMENT '身份类型',
  `PSR_BRDNO` varchar(10) DEFAULT NULL COMMENT '旅客登机号信息',
  `PSR_GROUP` varchar(6) DEFAULT NULL COMMENT '团体旅客标识、团体人数',
  `PSR_ICS` varchar(6) DEFAULT NULL COMMENT 'ics中记录信息',
  `PSR_CRS` varchar(6) DEFAULT NULL COMMENT 'crs中记录信息',
  `PSR_SEATNBR` varchar(50) DEFAULT NULL COMMENT '当前航站的座位号',
  `PSR_FFFR` varchar(22) DEFAULT NULL COMMENT '常旅客/asr旅客信息',
  `PSR_EFMN` varchar(45) DEFAULT NULL COMMENT '电子客票旅客',
  `PSR_BAGS` int(11) DEFAULT NULL COMMENT '行李总件数',
  `PSR_BAGWGT` varchar(10) DEFAULT NULL COMMENT '行李总重量',
  `PSR_CLASS` varchar(10) DEFAULT NULL COMMENT '旅客舱位信息',
  `PSR_CKIPID` varchar(10) DEFAULT NULL COMMENT '执行旅客操作的终端号',
  `PSR_OFFICE` varchar(6) DEFAULT NULL COMMENT '执行值机操作的办公室',
  `PSR_AGENT` varchar(20) DEFAULT NULL COMMENT '执行值机的代理号',
  `PSR_CKITIME` varchar(19) DEFAULT NULL COMMENT '执行值机时间信息',
  `PSR_SIP` varchar(20) DEFAULT NULL COMMENT '共享航班',
  `PSR_FOID_NONET` varchar(22) DEFAULT NULL COMMENT '非et旅客的身份证号',
  `PSR_SEG_SEATNBR` varchar(70) DEFAULT NULL COMMENT '旅客的座位信息',
  `FFQNO` varchar(22) DEFAULT NULL COMMENT '常客号',
  `DATASOURCE` varchar(50) DEFAULT NULL COMMENT '数据来源',
  `TELNO` varchar(100) DEFAULT NULL COMMENT '电话',
  `PAXCLASS` varchar(50) DEFAULT NULL COMMENT '舱位',
  `ADRESS` varchar(100) DEFAULT NULL COMMENT '居住地址',
  `CITY` varchar(100) DEFAULT NULL COMMENT '城市',
  `PROVINCE` varchar(100) DEFAULT NULL COMMENT '省份',
  `ICAO_CODE` varchar(4) DEFAULT NULL COMMENT '国家icao编码',
  `POSTCODE` varchar(100) DEFAULT NULL COMMENT '邮编',
  `EDI` varchar(50) DEFAULT NULL COMMENT '联程旅客标识',
  `ASSBY` varchar(255) DEFAULT NULL,
  `PSR_INF` varchar(50) DEFAULT NULL COMMENT '婴儿标识',
  `PSR_INFNAME` varchar(20) DEFAULT NULL COMMENT '婴儿姓名',
  `STCR` varchar(50) DEFAULT NULL COMMENT '担架旅客标识',
  `WL` varchar(50) DEFAULT NULL COMMENT '轮椅标识',
  `JMP` varchar(50) DEFAULT NULL COMMENT '占用折椅旅客标识',
  `SPECIAL_SEAT` varchar(50) DEFAULT NULL COMMENT '特殊座位标识',
  `SPECIAL_BG` varchar(50) DEFAULT NULL COMMENT '特殊行李标识',
  `SVC` varchar(50) DEFAULT NULL COMMENT '特殊服务',
  `CKI_CHG` varchar(50) DEFAULT NULL COMMENT '值机更改标识',
  `CMT` varchar(50) DEFAULT NULL COMMENT '旅客注释标识',
  `VIP` varchar(50) DEFAULT NULL COMMENT '贵宾旅客标识',
  `URES` varchar(50) DEFAULT NULL COMMENT '未订座旅客标识',
  `PSR_SBYNO` int(11) DEFAULT NULL COMMENT '候补号',
  `PSR_STDRS` varchar(4) DEFAULT NULL,
  `PSR_ACC` varchar(50) DEFAULT NULL COMMENT '值机标识',
  `PSR_SPML_ID` varchar(50) DEFAULT NULL COMMENT '特殊餐食标识',
  `PSR_SPML` varchar(80) DEFAULT NULL COMMENT '特殊餐食',
  `PSR_MSG` varchar(200) DEFAULT NULL COMMENT '旅客信息项',
  `PSR_PSM` varchar(200) DEFAULT NULL COMMENT '旅客服务信息',
  `PSR_PIL` varchar(80) DEFAULT NULL COMMENT '旅客信息清单项',
  `PSR_PCTC` varchar(200) DEFAULT NULL COMMENT '紧急联系信息项',
  `PSR_PSPT` varchar(80) DEFAULT NULL COMMENT '过境信息项',
  `PSR_NOTIFY` varchar(20) DEFAULT NULL COMMENT '广播通知消息',
  `PSR_BLND` varchar(50) DEFAULT NULL COMMENT '盲人旅客标识',
  `PSR_DEAF` varchar(50) DEFAULT NULL COMMENT '耳聋旅客标识',
  `PSR_EMIG` varchar(50) DEFAULT NULL COMMENT '移民旅客',
  `PSR_INAD` varchar(50) DEFAULT NULL COMMENT '不许可旅客',
  `PSR_WTYPE` varchar(4) DEFAULT NULL COMMENT '轮椅类型信息',
  `PSR_WCBD` varchar(80) DEFAULT NULL COMMENT '轮椅-干燥信息项',
  `PSR_WCBW` varchar(80) DEFAULT NULL COMMENT '轮椅-潮湿信息项',
  `PSR_WCMD` varchar(80) DEFAULT NULL COMMENT 'wcmp_item轮椅-手工信息项',
  `PSR_WCOB` varchar(80) DEFAULT NULL COMMENT '轮椅-机上信息项',
  `PSR_CTCA` varchar(80) DEFAULT NULL COMMENT 'ctca_item(代理人联系信息）',
  `PSR_RUSH` varchar(80) DEFAULT NULL COMMENT '速运行李标识',
  `PSR_HBPRBG` varchar(20) DEFAULT NULL COMMENT 'hbpr指令中行李带信息',
  `PSR_AVIH` varchar(50) DEFAULT NULL COMMENT '手提狗笼标识',
  `PSR_PETC` varchar(50) DEFAULT NULL COMMENT '宠物笼子标识',
  `PSR_BAGGAGE` varchar(30) DEFAULT NULL COMMENT '行李',
  `PSR_UNATTACH` varchar(50) DEFAULT NULL COMMENT '不跟人行李标识信息',
  `PSR_ARST` varchar(10) DEFAULT NULL COMMENT '分配/预留座位类型',
  `PSR_XASR` varchar(50) DEFAULT NULL COMMENT '取消asr旅客标识',
  `PSR_XABP` varchar(50) DEFAULT NULL COMMENT '取消abp旅客标识',
  `PSR_EXSTSEAT` varchar(8) DEFAULT NULL COMMENT '额外占座',
  `PSR_RST` varchar(5) DEFAULT NULL COMMENT '预留座位种类信息',
  `PSR_SPE` varchar(6) DEFAULT NULL COMMENT '座位个人喜好项',
  `PSR_ASOBOI` varchar(50) DEFAULT NULL COMMENT '被他人占用的座位标识信息',
  `PSR_OSR` varchar(10) DEFAULT NULL COMMENT '最初预定+d163座位项',
  `PSR_AEC` varchar(50) DEFAULT NULL COMMENT 'aec旅客标识',
  `PSR_SEA` varchar(50) DEFAULT NULL COMMENT '给aec旅客重新分配座位标识',
  `PSR_REA` varchar(50) DEFAULT NULL COMMENT '给aec旅客重新订座标识',
  `PSR_BSCT` varchar(50) DEFAULT NULL COMMENT '摇篮类型',
  `PSR_UDGRADE` varchar(20) DEFAULT NULL COMMENT '升降舱类型',
  `PSR_OFL` varchar(50) DEFAULT NULL COMMENT '被拉下旅客表示信息',
  `PSR_DEP` varchar(50) DEFAULT NULL COMMENT '拉下类型标识',
  `PSR_RTFI` varchar(20) DEFAULT NULL COMMENT '再值机到某航班信息',
  `PSR_RFFI` varchar(20) DEFAULT NULL COMMENT '从某航班再值机信息',
  `PSR_TSI` varchar(20) DEFAULT NULL COMMENT '旅行状态标识',
  `PSR_XRES` varchar(50) DEFAULT NULL COMMENT '取消订座标识',
  `PSR_XT` varchar(50) DEFAULT NULL COMMENT '取消转港标识信息',
  `PSR_CITYCANC` varchar(50) DEFAULT NULL COMMENT '城市取消标识',
  `PSR_VUDGRADE` varchar(50) DEFAULT NULL COMMENT '自愿升降舱标识',
  `PSR_EDI_WARN` varchar(80) DEFAULT NULL COMMENT 'edifact警告项',
  `PSR_INBOUND` varchar(40) DEFAULT NULL COMMENT '入港',
  `PSR_EDII` varchar(50) DEFAULT NULL COMMENT '进港联乘edi旅客标识',
  `PSR_OUTBOUND` varchar(200) DEFAULT NULL COMMENT '出港',
  `PSR_EDIO` varchar(50) DEFAULT NULL COMMENT '出港联乘edi旅客标识',
  `PSR_EDI_DEPT` varchar(3) DEFAULT NULL COMMENT 'edi旅客始发站',
  `PSR_EDI_DEPT_ZW` varchar(255) DEFAULT NULL COMMENT 'edi旅客始发站',
  `PSR_EDI_DEST` varchar(3) DEFAULT NULL COMMENT 'edi旅客到达站',
  `PSR_EDI_DEST_ZW` varchar(255) DEFAULT NULL COMMENT 'edi旅客到达站',
  `PNR_REF` varchar(6) DEFAULT NULL COMMENT 'icspnr记录编号',
  `DELETE_FLAG` varchar(50) DEFAULT NULL COMMENT '删除标志',
  `DELETE_FLT_ID` varchar(20) DEFAULT NULL COMMENT '删除航班id',
  `PSR_ARRIVE_TIME` varchar(19) DEFAULT NULL COMMENT '入库时间',
  `FILENAME` varchar(50) DEFAULT NULL COMMENT '原始数据包的文件名',
  `FILE_TIME` varchar(15) DEFAULT NULL COMMENT '文件时间',
  `CT_DT` varchar(19) DEFAULT NULL COMMENT '导入数据时间',
  `BZK_RKSJ` datetime DEFAULT NULL,
  `BZK_GXSJ` datetime DEFAULT NULL,
  `BZK_ZZJG` varchar(255) DEFAULT NULL,
  `BZK_SCBZ` varchar(255) DEFAULT NULL,
  `ZYK_SSXTMC` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_wb_ryswxx
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_wb_ryswxx`;
CREATE TABLE `t_bz_wb_ryswxx` (
  `SYSTEMID` varchar(100) NOT NULL COMMENT '主键',
  `YXTBH` varchar(255) DEFAULT NULL,
  `YYCSDM` varchar(21) DEFAULT NULL COMMENT '网吧代码',
  `YYCSMC` varchar(105) DEFAULT NULL COMMENT '网吧名称',
  `YYCSDZ` varchar(255) DEFAULT NULL,
  `YYCSXZQH` varchar(255) DEFAULT NULL,
  `YYCSXZQHMC` varchar(255) DEFAULT NULL,
  `SWRYXM` varchar(45) DEFAULT NULL COMMENT '上网人员姓名',
  `DZQH` varchar(9) DEFAULT NULL COMMENT '人员地址区号',
  `XZQHMC` varchar(255) DEFAULT NULL,
  `DZ` varchar(105) DEFAULT NULL COMMENT '人员地址',
  `ZJLX` varchar(5) DEFAULT NULL COMMENT '证件类型',
  `ZJLXDM` varchar(255) DEFAULT NULL,
  `ZJHM` varchar(27) DEFAULT NULL COMMENT '证件号码',
  `FZJGMC` varchar(105) DEFAULT NULL COMMENT '人员证件发证机关名称',
  `GJ` varchar(5) DEFAULT NULL COMMENT '国籍',
  `SWKSSJ` varchar(21) DEFAULT NULL COMMENT '上网开始时间',
  `SWZDH` varchar(48) DEFAULT NULL COMMENT '上网终端号',
  `XWSJ` varchar(21) DEFAULT NULL COMMENT '下网时间',
  `ENTERDB_TIME` datetime DEFAULT NULL COMMENT '入库时间',
  `HCK_TIME` datetime DEFAULT NULL COMMENT '核查时间',
  `INTHISDB_TIME` datetime DEFAULT NULL COMMENT '入数据中心库时间',
  `BZK_RKSJ` varchar(255) DEFAULT NULL,
  `BZK_GXSJ` varchar(255) DEFAULT NULL,
  `BZK_SCBZ` varchar(255) DEFAULT NULL,
  `BZK_ZZJG` varchar(255) DEFAULT NULL,
  `ZYK_SSXTMC` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_wb_wbzdxx
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_wb_wbzdxx`;
CREATE TABLE `t_bz_wb_wbzdxx` (
  `SYSTEMID` varchar(100) DEFAULT NULL,
  `YXTBH` varchar(255) DEFAULT NULL,
  `YYCSDM` varchar(21) DEFAULT NULL COMMENT '网吧代码',
  `YYCSMC` varchar(105) DEFAULT NULL COMMENT '网吧名',
  `DZQH` varchar(9) DEFAULT NULL COMMENT '地址区号',
  `XZQHMC` varchar(255) DEFAULT NULL,
  `DZ` varchar(105) DEFAULT NULL COMMENT '地址',
  `CKIPDZ` varchar(59) DEFAULT NULL COMMENT 'ip地址',
  `SSGAJGJGDM` varchar(18) DEFAULT NULL COMMENT '所属公安机关机构代码',
  `SSWJBMMC` varchar(105) DEFAULT NULL,
  `ENTERDB_TIME` datetime DEFAULT NULL,
  `BZK_RKSJ` varchar(255) DEFAULT NULL,
  `BZK_GXSJ` varchar(255) DEFAULT NULL,
  `BZK_SCBZ` varchar(255) DEFAULT NULL,
  `BZK_ZZJG` varchar(255) DEFAULT NULL,
  `ZYK_SSXTMC` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
