/*
Navicat MySQL Data Transfer

Source Server         : jwzh
Source Server Version : 50538
Source Host           : localhost:3306
Source Database       : source_ck

Target Server Type    : MYSQL
Target Server Version : 50538
File Encoding         : 65001

Date: 2017-03-24 16:34:27
*/

SET FOREIGN_KEY_CHECKS=0;
DROP Database IF EXISTS `source_ck`;
CREATE Database `source_ck`;
use source_ck;
-- ----------------------------
-- Table structure for t_bz_ck_edzsl
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_ck_edzsl`;
CREATE TABLE `t_bz_ck_edzsl` (
  `SYSTEMID` varchar(50) NOT NULL COMMENT '系统主键',
  `ABOUT_LZ_DATE` varchar(75) DEFAULT NULL COMMENT '预约领证时间',
  `ACCEPT_DATE` date DEFAULT NULL COMMENT '受理日期',
  `ACCEPT_ORG_ID` varchar(12) DEFAULT NULL COMMENT '受理单位代码',
  `ACCEPT_PSN` varchar(45) DEFAULT NULL COMMENT '受理人',
  `ACCEPT_PSN_ID` varchar(21) DEFAULT NULL COMMENT '受理人编号',
  `ACCEPT_UNIT` varchar(90) DEFAULT NULL COMMENT '受理单位名称',
  `ADDR_REGION_ID` varchar(9) DEFAULT NULL COMMENT '住址.省市县代码',
  `APPLIED_REASON` varchar(90) DEFAULT NULL COMMENT '申领原因',
  `APPLIED_REASON_CODE` varchar(2) DEFAULT NULL COMMENT '申领原因代码',
  `ARRIVE_DATE` date DEFAULT NULL COMMENT '证件到达日期',
  `CARD_MAN_ID` varchar(21) DEFAULT NULL COMMENT '证件管理号',
  `YXTBH` varchar(22) DEFAULT NULL,
  `CASE_KIND` varchar(90) DEFAULT NULL COMMENT '制证类型',
  `CASE_KIND_CODE` varchar(2) DEFAULT NULL COMMENT '制证类型代码',
  `CHIP_NO` varchar(90) DEFAULT NULL COMMENT '芯片号',
  `CWZJBZ` varchar(1) DEFAULT NULL,
  `DATAUPLOAD_DATE` datetime DEFAULT NULL COMMENT '打包日期',
  `DATA_PACKAGE_NO` varchar(38) DEFAULT NULL COMMENT '数据包编号',
  `DBDW` varchar(100) DEFAULT NULL COMMENT '代办单位',
  `DBRPID` varchar(27) DEFAULT NULL COMMENT '代办人公民身份号码',
  `DBRRELATION` varchar(45) DEFAULT NULL COMMENT '代办人与受理人关系',
  `DBRXM` varchar(45) DEFAULT NULL COMMENT '代办人姓名',
  `DBYY` varchar(45) DEFAULT NULL COMMENT '代办原因',
  `DOB` date DEFAULT NULL COMMENT '出生日期',
  `DSBM` varchar(6) DEFAULT NULL COMMENT '地市编码',
  `FBNO` varchar(20) DEFAULT NULL COMMENT '发票编号',
  `FINGER_MARK_ID` varchar(21) DEFAULT NULL,
  `FINISH_DATE` date DEFAULT NULL COMMENT '制作完成日期',
  `FJ_READCARD_DATE` datetime DEFAULT NULL COMMENT '分局录入时间',
  `FJ_READCARD_MAN` varchar(45) DEFAULT NULL COMMENT '分局录入人',
  `FJ_READCARD_UNIT` varchar(120) DEFAULT NULL COMMENT '分局录入单位',
  `FULLADDR` varchar(256) DEFAULT NULL COMMENT '住址',
  `GENDER` varchar(15) DEFAULT NULL COMMENT '性别',
  `GENDER_CODE` varchar(2) DEFAULT NULL COMMENT '性别代码',
  `GET_PID_TYPE` varchar(90) DEFAULT NULL COMMENT '领证方式',
  `GET_PID_TYPE_CODE` varchar(2) DEFAULT NULL COMMENT '领证方式代码',
  `GIVEN_OUT_PSN` varchar(45) DEFAULT NULL COMMENT '发放人',
  `GIVEN_OUT_UNIT` varchar(90) DEFAULT NULL COMMENT '发放单位',
  `HCK_GXSJ` datetime DEFAULT NULL COMMENT '缓冲库更新时间',
  `HCK_RKSJ` datetime DEFAULT NULL COMMENT '缓冲库入库时间',
  `HJPCS_CHECKED_DATE` date DEFAULT NULL COMMENT '户籍派出所审核日期',
  `HJPCS_CHECKER` varchar(45) DEFAULT NULL COMMENT '户籍派出所审核人',
  `HJPCS_CHECK_RESULT` varchar(15) DEFAULT NULL COMMENT '户籍派出所审核情况',
  `HJPCS_SENDDATE` date DEFAULT NULL COMMENT '户籍派出所发送日期',
  `HJPCS_SEND_FLAG` varchar(9) DEFAULT NULL COMMENT '户籍派出所发送标识',
  `HJZXBZ` varchar(1) DEFAULT NULL COMMENT '?户籍注销标志',
  `IF_READCARD` varchar(2) DEFAULT NULL COMMENT '是否录入',
  `IMAGE_ID` varchar(21) DEFAULT NULL COMMENT '照片图像号',
  `ISSUED_UNIT` varchar(90) DEFAULT NULL COMMENT '证件签发机关',
  `ISTSRY` varchar(50) DEFAULT NULL COMMENT '是否特殊人群',
  `ISVALID` varchar(1) DEFAULT NULL COMMENT '是否有效',
  `KPFLAG` varchar(1) DEFAULT NULL COMMENT '开票标识',
  `LSSFZSLBS` varchar(2) DEFAULT NULL,
  `LSZJBZ` varchar(1) DEFAULT NULL,
  `LZFS_BDYY` varchar(90) DEFAULT NULL COMMENT '领证方式变动原因',
  `LZ_DATE` date DEFAULT NULL COMMENT '领证日期',
  `LZ_DB_FALG` varchar(10) DEFAULT NULL COMMENT '领证信息是否打包标识',
  `LZ_NAME` varchar(45) DEFAULT NULL COMMENT '领证人姓名',
  `LZ_PID` varchar(18) DEFAULT NULL COMMENT '领证人公民身份号码',
  `MEMO1` varchar(300) DEFAULT NULL COMMENT '备注字段',
  `META_ADDR_ID` varchar(21) DEFAULT NULL COMMENT '地址编号',
  `NAME` varchar(45) DEFAULT NULL COMMENT '姓名',
  `NATION` varchar(15) DEFAULT NULL COMMENT '民族',
  `NATION_CODE` varchar(2) DEFAULT NULL COMMENT '民族代码',
  `NOTIFY_DATE` date DEFAULT NULL COMMENT '通知日期',
  `NOTIFY_TYPE` varchar(60) DEFAULT NULL COMMENT '通知方式',
  `OLD_CASE_ID` varchar(22) DEFAULT NULL COMMENT '原受理号',
  `OPERATION` varchar(20) DEFAULT NULL COMMENT '缓冲库操作方式',
  `ORG_ID` varchar(12) DEFAULT NULL COMMENT '管理机构派出所代码',
  `OTHER_LZFS` varchar(90) DEFAULT NULL COMMENT '其它领证方式',
  `PACKAGED_NUM` int(11) DEFAULT NULL COMMENT '打包数据目',
  `PACKAGE_UPLOADED` varchar(2) DEFAULT NULL COMMENT '打包上传状态',
  `PAUSECHECK` varchar(1) DEFAULT NULL COMMENT '撤消标识',
  `PCS` varchar(90) DEFAULT NULL COMMENT '管理机构派出所',
  `PERSON_ID` varchar(30) DEFAULT NULL COMMENT '人员编号',
  `PID` varchar(18) DEFAULT NULL COMMENT '公民身份号码',
  `PID_KIND` int(11) DEFAULT NULL COMMENT '证件类型',
  `PID_STATUS` varchar(150) DEFAULT NULL COMMENT '证件状态',
  `QFJG_CHECKED_DATE` date DEFAULT NULL COMMENT '签发机关审核日期',
  `QFJG_CHECKER` varchar(45) DEFAULT NULL COMMENT '签发机关审核人',
  `QFJG_CHECK_RESULT` varchar(15) DEFAULT NULL COMMENT '签发机关审核情况',
  `QFJG_ISSUED_DATE` date DEFAULT NULL COMMENT '签发机关签发日期',
  `QFJG_ISSUER` varchar(45) DEFAULT NULL COMMENT '签发机关签发人',
  `READCARDDATE` date DEFAULT NULL COMMENT '录入时间',
  `READCARDPSN` varchar(45) DEFAULT NULL COMMENT '录入人',
  `RECEIVER` varchar(45) DEFAULT NULL COMMENT '收件人',
  `RECEIVE_ADDR` varchar(120) DEFAULT NULL COMMENT '收件人地址',
  `RECEIVE_DETAIL` varchar(120) DEFAULT NULL COMMENT '收件人祥址',
  `RECEIVE_NO` varchar(15) DEFAULT NULL COMMENT '收件人序号',
  `RECEIVE_PID` varchar(18) DEFAULT NULL COMMENT '收件人身份证号',
  `RECEIVE_QU` varchar(120) DEFAULT NULL COMMENT '收件人区划',
  `RECEIVE_TEL` varchar(100) DEFAULT NULL COMMENT '收件人联系电话',
  `RECEIVE_ZIP` varchar(30) DEFAULT NULL COMMENT '收件人邮政编码',
  `RELATION_LZ` varchar(75) DEFAULT NULL COMMENT '领证人与申领人关系',
  `SJ_CHECKED_DATE` date DEFAULT NULL COMMENT '市局审核日期',
  `SJ_CHECKER` varchar(45) DEFAULT NULL COMMENT '市局审核人',
  `SJ_CHECK_RESULT` varchar(15) DEFAULT NULL COMMENT '市局审核情况',
  `SJ_READCARD_DATE` date DEFAULT NULL COMMENT '市局录入时间',
  `SJ_READCARD_MAN` varchar(45) DEFAULT NULL COMMENT '市局录入人',
  `SJ_READCARD_UNIT` varchar(120) DEFAULT NULL,
  `SLDWSSFXJ_DWDM` varchar(12) DEFAULT NULL COMMENT '受理单位代码',
  `SLDWSSFXJ_DWMC` varchar(120) DEFAULT NULL COMMENT '受理单位',
  `STATUS_CODE` varchar(2) DEFAULT NULL COMMENT '证件状态代码',
  `TEL` varchar(90) DEFAULT NULL COMMENT '联系电话',
  `UL_END_DATE` date DEFAULT NULL COMMENT '有效期限截止日期',
  `UL_FROM_DATE` date DEFAULT NULL COMMENT '有效期限起始日期',
  `USEFUL_LIFE` varchar(15) DEFAULT NULL COMMENT '证件有效期限',
  `WHEN_CANCELLED` date DEFAULT NULL COMMENT '撤消时间',
  `WHEN_OPERATED` date DEFAULT NULL COMMENT '创建时间',
  `XSBBJXT` varchar(1) DEFAULT NULL,
  `YWLSH` varchar(2) DEFAULT NULL COMMENT '业务流水号',
  `ZJFFBWJM` varchar(105) DEFAULT NULL,
  `ZJFFDBSJ` datetime DEFAULT NULL,
  `ZXBGBZ` varchar(1) DEFAULT NULL,
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  `ISSUED_UNIT_GABZ` varchar(12) DEFAULT NULL,
  `ACCEPT_ORG_ID_GABZ` varchar(12) DEFAULT NULL,
  `ORG_ID_GABZ` varchar(12) DEFAULT NULL,
  `GIVEN_OUT_UNIT_GABZ` varchar(12) DEFAULT NULL,
  `SLDWSSFXJ_DWDM_GABZ` varchar(12) DEFAULT NULL,
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_ck_lszsl
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_ck_lszsl`;
CREATE TABLE `t_bz_ck_lszsl` (
  `SYSTEMID` varchar(50) NOT NULL COMMENT '系统主键',
  `ABOUT_LZ_DAYS` int(11) DEFAULT NULL COMMENT '预约领证天数',
  `ACCEPT_DATE` datetime DEFAULT NULL COMMENT '经办时间',
  `ACCEPT_ORG_ID` varchar(12) DEFAULT NULL COMMENT '经办人单位编号',
  `ACCEPT_PSN` varchar(45) DEFAULT NULL COMMENT '经办人',
  `ADDRESS` varchar(220) DEFAULT NULL COMMENT '住址',
  `BZ` varchar(100) DEFAULT NULL COMMENT '备注',
  `CARDNO` varchar(17) DEFAULT NULL COMMENT '卡体号',
  `CARD_MAN_ID` varchar(22) DEFAULT NULL COMMENT '证件管理号',
  `YXTBH` varchar(33) DEFAULT NULL,
  `CHECKER` varchar(45) DEFAULT NULL COMMENT '审核人',
  `CHECK_DATE` datetime DEFAULT NULL COMMENT '审核时间',
  `CHECK_RESULT` varchar(15) DEFAULT NULL COMMENT '审核结果',
  `DB_NAME` varchar(45) DEFAULT NULL COMMENT '代办人姓名',
  `DB_PID` varchar(45) DEFAULT NULL COMMENT '代办人证号',
  `DB_RELATION` varchar(45) DEFAULT NULL COMMENT '与代办人关系',
  `DOB` date DEFAULT NULL COMMENT '出生日期',
  `DSBM` varchar(6) DEFAULT NULL COMMENT '地市编码',
  `ERROR_DES` varchar(150) DEFAULT NULL COMMENT '错误描述',
  `ERROR_KIND` varchar(50) DEFAULT NULL COMMENT '错误类别',
  `FBNO` varchar(20) DEFAULT NULL,
  `FIND_ERR_DATE` datetime DEFAULT NULL COMMENT '发现错误时间',
  `FIND_ERR_PSN` varchar(45) DEFAULT NULL COMMENT '发现错误人',
  `FIND_ERR_UNIT` varchar(120) DEFAULT NULL COMMENT '发现错误单位',
  `FIRSTOLD_CASE_ID` varchar(22) DEFAULT NULL COMMENT '二代证受理号',
  `FPCOPY` int(11) DEFAULT NULL COMMENT '发票份数',
  `FPFEE` decimal(10,2) DEFAULT NULL COMMENT '发票金额',
  `FPINFO` varchar(256) DEFAULT NULL COMMENT '发票信息',
  `FPMEMO` varchar(100) DEFAULT NULL COMMENT '发票备注',
  `FPTYPE` varchar(80) DEFAULT NULL COMMENT '发票类型',
  `GENDER` varchar(15) DEFAULT NULL COMMENT '性别',
  `GIVEN_OUT_PSN` varchar(45) DEFAULT NULL COMMENT '发证人',
  `GIVEN_OUT_UNIT` varchar(120) DEFAULT NULL COMMENT '发证单位',
  `HCK_GXSJ` datetime DEFAULT NULL COMMENT '缓冲库更新时间',
  `HCK_RKSJ` datetime DEFAULT NULL COMMENT '缓冲库入库时间',
  `ISSUED_UNIT` varchar(75) DEFAULT NULL COMMENT '签发机关',
  `ISSUER` varchar(45) DEFAULT NULL COMMENT '签发人',
  `LZ_DATE` date DEFAULT NULL COMMENT '领证时间',
  `LZ_NAME` varchar(45) DEFAULT NULL COMMENT '领证人',
  `LZ_PID` varchar(18) DEFAULT NULL,
  `LZ_RELATION` varchar(45) DEFAULT NULL COMMENT '与领证人关系',
  `MAILNO` varchar(20) DEFAULT NULL COMMENT '邮件号码',
  `NAME` varchar(45) DEFAULT NULL COMMENT '姓名',
  `NATION` varchar(15) DEFAULT NULL COMMENT '民族',
  `OLD_CASE_ID` varchar(23) DEFAULT NULL COMMENT '原受理号',
  `OPERATION` varchar(20) DEFAULT NULL COMMENT '缓冲库操作方式',
  `ORG_ID` varchar(12) DEFAULT NULL COMMENT '户籍派出所编号',
  `PERSON_ID` varchar(21) DEFAULT NULL COMMENT '人员编号',
  `PHOTO_ID` varchar(21) DEFAULT NULL COMMENT '图像编号',
  `PID` varchar(18) DEFAULT NULL COMMENT '公民身份号码',
  `PID_STATUS` varchar(100) DEFAULT NULL COMMENT '证件状态',
  `PRINTNUM` int(11) DEFAULT NULL COMMENT '镜像打印次数',
  `PRINTPSN` varchar(45) DEFAULT NULL COMMENT '镜像打印人',
  `PRINT_DATE` datetime DEFAULT NULL COMMENT '镜像打印时间',
  `RECEIVER` varchar(45) DEFAULT NULL COMMENT '收件人',
  `RECEIVE_ADDR` varchar(300) DEFAULT NULL COMMENT '收件人地址',
  `RECEIVE_TEL` varchar(60) DEFAULT NULL COMMENT '收件人联系电话',
  `RECEIVE_ZIP` varchar(30) DEFAULT NULL COMMENT '收件人邮编',
  `SENDTYPE` varchar(12) DEFAULT NULL COMMENT '区内、区外',
  `TEL` varchar(60) DEFAULT NULL COMMENT '联系电话',
  `UL_END_DATE` datetime DEFAULT NULL COMMENT '有效期限截止时间',
  `UL_FROM_DATE` datetime DEFAULT NULL COMMENT '有效期限起始时间',
  `WHBS` varchar(2) DEFAULT NULL COMMENT '维护升级库标识',
  `WHEN_OPERATED` datetime DEFAULT NULL COMMENT '录入时间',
  `WHSJ` datetime DEFAULT NULL COMMENT '维护升级库时间',
  `WHY_CANCELED` varchar(100) DEFAULT NULL COMMENT '撤消原因',
  `XXBS` varchar(3) DEFAULT NULL COMMENT '信息标识',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  `GIVEN_OUT_UNIT_GABZ` varchar(12) DEFAULT NULL,
  `ISSUED_UNIT_GABZ` varchar(12) DEFAULT NULL,
  `ACCEPT_ORG_ID_GABZ` varchar(12) DEFAULT NULL,
  `ORG_ID_GABZ` varchar(12) DEFAULT NULL,
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_ck_ryjbxx
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_ck_ryjbxx`;
CREATE TABLE `t_bz_ck_ryjbxx` (
  `APPLYNO_QC` varchar(21) DEFAULT NULL COMMENT '受理迁出编号',
  `APPLYNO_QR` varchar(21) DEFAULT NULL COMMENT '受理迁入编号',
  `BLOODTYPE` varchar(9) DEFAULT NULL COMMENT '血型',
  `BLOODTYPE_ZW` varchar(255) DEFAULT NULL,
  `BLOODTYPE_CODE` varchar(9) DEFAULT NULL,
  `BORN_CARD_NO` varchar(75) DEFAULT NULL COMMENT '出生证号码',
  `BUILDING_ID` varchar(21) DEFAULT NULL COMMENT '小区（楼房）编号',
  `BUILDING_NAME` varchar(120) DEFAULT NULL COMMENT '小区（楼房）',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `CELL` varchar(60) DEFAULT NULL COMMENT '单元',
  `DATE_OF_DEATH` date DEFAULT NULL COMMENT '死亡日期',
  `DEATH_NO` varchar(75) DEFAULT NULL COMMENT '死亡证明编号',
  `DOB` date DEFAULT NULL COMMENT '出生日期',
  `DOB_TIME` varchar(9) DEFAULT NULL COMMENT '出生时分',
  `DSBM` varchar(6) DEFAULT NULL COMMENT '地市编码',
  `DUTY_AREA_ID` varchar(21) DEFAULT NULL COMMENT '责任区编号',
  `DUTY_AREA_NAME` varchar(120) DEFAULT NULL COMMENT '责任区',
  `EDU_DEGREE` varchar(75) DEFAULT NULL COMMENT '文化程度',
  `EDU_DEGREE_ZW` varchar(255) DEFAULT NULL,
  `EDU_DEGREE_GABZ` varchar(2) DEFAULT NULL COMMENT '文化程度_公安标准',
  `ENLISTED` varchar(15) DEFAULT NULL COMMENT '兵役状况',
  `ENLISTED_ZW` varchar(255) DEFAULT NULL,
  `ENLISTED_CODE` varchar(15) DEFAULT NULL,
  `FA_NAME` varchar(45) DEFAULT NULL COMMENT '父亲姓名',
  `FA_PERSON_ID` varchar(21) DEFAULT NULL COMMENT '父亲人员编号',
  `FA_PID` varchar(18) DEFAULT NULL COMMENT '父亲公民身份号码',
  `FLOOR` int(11) DEFAULT NULL COMMENT '层',
  `FROM_ADDR` varchar(300) DEFAULT NULL COMMENT '迁来地',
  `FROM_COUNTRY_ID` varchar(6) DEFAULT NULL COMMENT '迁来地（国家地区）',
  `FROM_COUNTRY_ID_ZW` varchar(255) DEFAULT NULL COMMENT '迁来地（国家地区）',
  `FROM_COUNTRY_ID_GABZ` varchar(3) DEFAULT NULL COMMENT '迁来地（国家地区）_公安标准',
  `FROM_ORG_ID` varchar(12) DEFAULT NULL COMMENT '迁来地（组织机构）',
  `FROM_ORG_ID_ZW` varchar(255) DEFAULT NULL COMMENT '迁来地（组织机构）',
  `FROM_ORG_ID_GABZ` varchar(12) DEFAULT NULL COMMENT '迁来地（组织机构）_公安标准',
  `FROM_PLACE_ID` varchar(12) DEFAULT NULL COMMENT '迁来地（居村委）',
  `FROM_PLACE_ID_ZW` varchar(255) DEFAULT NULL COMMENT '迁来地（居村委）',
  `FROM_REGION_ID` varchar(15) DEFAULT NULL COMMENT '迁来地（省市县区）',
  `FROM_REGION_ID_ZW` varchar(255) DEFAULT NULL COMMENT '迁来地（省市县区）',
  `FROM_REGION_ID_GABZ` varchar(15) DEFAULT NULL COMMENT '迁来地（省市县区）_公安标准',
  `FULL_ADDR` varchar(300) DEFAULT NULL COMMENT '地址全称',
  `GENDER` varchar(21) DEFAULT NULL COMMENT '性别',
  `GENDER_ZW` varchar(255) DEFAULT NULL,
  `GENDER_GABZ` varchar(1) DEFAULT NULL COMMENT '性别_公安标准',
  `GURARDIAN_1` varchar(45) DEFAULT NULL COMMENT '监护人1姓名',
  `GURARDIAN_1_ID` varchar(21) DEFAULT NULL COMMENT '监护人1人员编号',
  `GURARDIAN_1_PID` varchar(18) DEFAULT NULL COMMENT '监护人1公民身份号码',
  `GURARDIAN_2` varchar(45) DEFAULT NULL COMMENT '监护人2姓名',
  `GURARDIAN_2_ID` varchar(21) DEFAULT NULL COMMENT '监护人2人员编号',
  `GURARDIAN_2_PID` varchar(18) DEFAULT NULL COMMENT '监护人2公民身份号码',
  `HAOZUO` varchar(100) DEFAULT NULL COMMENT '门牌号',
  `HAOZUO_DETAIL` varchar(300) DEFAULT NULL COMMENT '详址',
  `HAOZUO_NO` int(11) DEFAULT NULL COMMENT '门牌号码',
  `HEIGHT` int(11) DEFAULT NULL COMMENT '身高',
  `HK_KIND` varchar(30) DEFAULT NULL COMMENT '户口性质（农业，非农业）',
  `HOWLEFTADDR` text COMMENT '何时何因迁往何地',
  `HOWTOADDR` text COMMENT '何时何因由何地迁来本址',
  `HOWTOCITY` text COMMENT '何时何因由何地迁来本市县',
  `HU_ADDR` varchar(300) DEFAULT NULL COMMENT '户籍地址',
  `HU_ID` varchar(21) DEFAULT NULL COMMENT '户编号',
  `HU_ID_NEW` varchar(20) DEFAULT NULL COMMENT '户号',
  `HU_KIND_CODE` varchar(5) DEFAULT NULL COMMENT '户别',
  `HU_KIND_NAME` varchar(9) DEFAULT NULL COMMENT '户别',
  `HU_MASTER_ID` varchar(21) DEFAULT NULL COMMENT '户主人员编号',
  `HU_MASTER_NAME` varchar(45) DEFAULT NULL COMMENT '户主姓名',
  `HU_MASTER_PID` varchar(30) DEFAULT NULL COMMENT '户主公民身份号码',
  `HU_WHEN_CANCELLED` date DEFAULT NULL COMMENT '销户时间',
  `HU_WHEN_REGISTERED` date DEFAULT NULL COMMENT '立户时间',
  `HYLB` varchar(150) DEFAULT NULL COMMENT '行业类别',
  `INCITY_BDYY` varchar(75) DEFAULT NULL COMMENT '何因来本市（名称）',
  `INCITY_BDYY_CODE` varchar(5) DEFAULT NULL COMMENT '何因来本市（代码）',
  `INCITY_CITY` varchar(10) DEFAULT NULL COMMENT '何地来本市（省市县区代码）',
  `INCITY_CITY_ZW` varchar(255) DEFAULT NULL COMMENT '何地来本市（省市县区代码）',
  `INCITY_CITY_GABZ` varchar(6) DEFAULT NULL COMMENT '何地来本市（省市县区代码）_公安标准',
  `INCITY_COUNTRY` varchar(6) DEFAULT NULL COMMENT '何地来本市（国家地区代码）',
  `INCITY_COUNTRY_ZW` varchar(255) DEFAULT NULL COMMENT '何地来本市（国家地区代码）',
  `INCITY_COUNTRY_GABZ` varchar(3) DEFAULT NULL COMMENT '何地来本市（国家地区代码）_公安标准',
  `INCITY_DATE` date DEFAULT NULL COMMENT '何时来本市',
  `INCITY_DETAIL` varchar(300) DEFAULT NULL COMMENT '何地来本市',
  `IN_APP_NAME` varchar(45) DEFAULT NULL COMMENT '申请人姓名',
  `IN_APP_PID` varchar(18) DEFAULT NULL COMMENT '申请人公民身份号码',
  `IN_CATEGORY` varchar(75) DEFAULT NULL COMMENT '迁入原因',
  `IN_CATEGORY_CODE` varchar(5) DEFAULT NULL COMMENT '迁入原因代码',
  `IN_KIND_CODE` varchar(3) DEFAULT NULL COMMENT '迁入类别代码',
  `IN_QY_NO` varchar(30) DEFAULT NULL COMMENT '迁移证编号',
  `IN_SCOPE_CODE` varchar(2) DEFAULT NULL COMMENT '变动范围',
  `IN_ZQ_NO` varchar(30) DEFAULT NULL COMMENT '准迁证编号',
  `JOB` varchar(75) DEFAULT NULL COMMENT '职业',
  `JOB_TYPE` varchar(150) DEFAULT NULL COMMENT '职业类别',
  `JOB_TYPE_ZW` varchar(255) DEFAULT NULL,
  `JOB_TYPE_CODE` varchar(150) DEFAULT NULL,
  `LH_KIND` varchar(9) DEFAULT NULL COMMENT '落户类别（常口、持证）',
  `MARRIAGE` varchar(30) DEFAULT NULL COMMENT '婚姻状况',
  `MARRIAGE_ZW` varchar(255) DEFAULT NULL COMMENT '婚姻状况',
  `MARRIAGE_GABZ` varchar(2) DEFAULT NULL COMMENT '婚姻状况_公安标准',
  `MASTER_RELATION` varchar(75) DEFAULT NULL COMMENT '与户主关系',
  `MASTER_RELATION_ZW` varchar(255) DEFAULT NULL,
  `MASTER_RELATION_CODE` varchar(75) DEFAULT NULL,
  `MA_NAME` varchar(45) DEFAULT NULL COMMENT '母亲姓名',
  `MA_PERSON_ID` varchar(21) DEFAULT NULL COMMENT '母亲人员编号',
  `MA_PID` varchar(18) DEFAULT NULL COMMENT '母亲公民身份号码',
  `META_ADDR_ID` varchar(21) DEFAULT NULL COMMENT '地址编号',
  `NAME` varchar(45) DEFAULT NULL COMMENT '姓名',
  `NAME_PY` varchar(75) DEFAULT NULL COMMENT '姓名拼音',
  `NATAL_CARD_DATE` date DEFAULT NULL COMMENT '出生证签发日期',
  `NATAL_COUNTRY` varchar(150) DEFAULT NULL COMMENT '出生地（国家地区）',
  `NATAL_COUNTRY_ZW` varchar(255) DEFAULT NULL COMMENT '出生地（国家地区）',
  `NATAL_COUNTRY_GABZ` varchar(3) DEFAULT NULL COMMENT '出生地（国家地区）_公安标准',
  `NATAL_PLACE` varchar(150) DEFAULT NULL COMMENT '出生地（省市县区）',
  `NATAL_PLACE_ZW` varchar(255) DEFAULT NULL COMMENT '出生地（省市县区）',
  `NATAL_PLACE_GABZ` varchar(6) DEFAULT NULL COMMENT '出生地（省市县区）_公安标准',
  `NATAL_XIANG` varchar(150) DEFAULT NULL COMMENT '出生地详址',
  `NATION` varchar(15) DEFAULT NULL COMMENT '民族',
  `NATION_ZW` varchar(255) DEFAULT NULL COMMENT '民族',
  `NATION_GABZ` varchar(2) DEFAULT NULL COMMENT '民族_公安标准',
  `NATIVE_COUNTRY` varchar(150) DEFAULT NULL COMMENT '籍贯（国家地区）',
  `NATIVE_COUNTRY_ZW` varchar(255) DEFAULT NULL COMMENT '籍贯（国家地区）',
  `NATIVE_COUNTRY_GABZ` varchar(3) DEFAULT NULL COMMENT '籍贯（国家地区）_公安标准',
  `NATIVE_PLACE` varchar(150) DEFAULT NULL COMMENT '籍贯（省市县区）',
  `NATIVE_PLACE_ZW` varchar(255) DEFAULT NULL COMMENT '籍贯（省市县区）',
  `NATIVE_PLACE_GABZ` varchar(6) DEFAULT NULL COMMENT '籍贯（省市县区）_公安标准',
  `NOW_SIGN` varchar(1) DEFAULT NULL COMMENT '最近标志（1：当前）',
  `OLD_PID_END_DATE` date DEFAULT NULL COMMENT '一代证截止日期',
  `OLD_PID_ISSUE_DATE` date DEFAULT NULL COMMENT '一代证签发日期',
  `OLD_PID_ISSUE_UNIT_NAME` varchar(120) DEFAULT NULL COMMENT '一代证签发单位',
  `OLD_PID_USEFUL_LIFE` varchar(9) DEFAULT NULL COMMENT '一代证有效期限',
  `ORG_ID` varchar(12) DEFAULT NULL COMMENT '派出所代码',
  `ORG_ID_ZW` varchar(255) DEFAULT NULL,
  `ORG_ID_GABZ` varchar(12) DEFAULT NULL COMMENT '派出所代码_公安标准',
  `ORG_NAME` varchar(120) DEFAULT NULL COMMENT '派出所',
  `OUT_APP_NAME` varchar(45) DEFAULT NULL COMMENT '申请人姓名',
  `OUT_APP_PID` varchar(18) DEFAULT NULL COMMENT '申请人公民身份号码',
  `OUT_CATEGORY` varchar(75) DEFAULT NULL COMMENT '迁出原因',
  `OUT_CATEGORY_CODE` varchar(5) DEFAULT NULL COMMENT '迁出原因代码',
  `OUT_KIND_CODE` varchar(3) DEFAULT NULL COMMENT '迁出类别代码',
  `OUT_QY_NO` varchar(30) DEFAULT NULL COMMENT '迁移证编号',
  `OUT_SCOPE_CODE` varchar(3) DEFAULT NULL COMMENT '变动范围',
  `OUT_SCOPE_CODE_ZW` varchar(255) DEFAULT NULL,
  `OUT_ZQ_NO` varchar(30) DEFAULT NULL COMMENT '准迁证编号',
  `PENDING_CARD` varchar(45) DEFAULT NULL COMMENT '持证件名称',
  `PENDING_CARD_NO` varchar(45) DEFAULT NULL COMMENT '持证件号码',
  `PENDING_CAUSE` varchar(75) DEFAULT NULL COMMENT '持证件原因',
  `PENDING_KIND` varchar(45) DEFAULT NULL COMMENT '持证类别',
  `PERSON_ID` varchar(21) DEFAULT NULL COMMENT '人员编号',
  `PHOTO_ID` varchar(21) DEFAULT NULL COMMENT '相片编号',
  `PID` varchar(30) DEFAULT NULL COMMENT '公民身份号码',
  `PID_APPLY_REASON` varchar(75) DEFAULT NULL COMMENT '二代证申领原因',
  `PID_END_DATE` date DEFAULT NULL COMMENT '二代证截止日期',
  `PID_INFO` varchar(18) DEFAULT NULL COMMENT '身份证缴销',
  `PID_ISSUE_DATE` date DEFAULT NULL COMMENT '二代证签发日期',
  `PID_ISSUE_UNIT_NAME` varchar(120) DEFAULT NULL,
  `PID_REC_DATE` date DEFAULT NULL COMMENT '二代证缴销日期',
  `PID_REC_REASON` varchar(75) DEFAULT NULL COMMENT '二代证缴销原因',
  `PID_USEFUL_LIFE` varchar(9) DEFAULT NULL COMMENT '二代证有效期限',
  `PO_NAME` varchar(45) DEFAULT NULL COMMENT '配偶姓名',
  `PO_PERSON_ID` varchar(21) DEFAULT NULL COMMENT '配偶人员编号',
  `PO_PID` varchar(18) DEFAULT NULL COMMENT '配偶公民身份号码',
  `PRE_HK_KIND` varchar(30) DEFAULT NULL COMMENT '迁入前户口性质',
  `PRE_HU_ID` varchar(21) DEFAULT NULL COMMENT '迁入前户编号',
  `PRE_LH_KIND` varchar(9) DEFAULT NULL COMMENT '迁入前落户类别',
  `PRE_PERSON_ID` varchar(21) DEFAULT NULL COMMENT '迁入前人员编号',
  `PROPERTY` varchar(30) DEFAULT NULL COMMENT '启用属性',
  `QU` varchar(120) DEFAULT NULL COMMENT '区县',
  `QU_ZW` varchar(255) DEFAULT NULL COMMENT '区县',
  `QUXCUN` varchar(120) DEFAULT NULL COMMENT '区乡村',
  `QUXCUN_ID` varchar(12) DEFAULT NULL COMMENT '区乡村编号',
  `QU_GABZ` varchar(12) DEFAULT NULL,
  `QU_ID` varchar(6) DEFAULT NULL COMMENT '省市县区',
  `QU_ID_ZW` varchar(255) DEFAULT NULL,
  `QU_ID_GABZ` varchar(6) DEFAULT NULL COMMENT '省市县区_公安标准',
  `RELIGION` varchar(15) DEFAULT NULL COMMENT '宗教信仰',
  `RELIGION_ZW` varchar(255) DEFAULT NULL,
  `RELIGION_CODE` varchar(15) DEFAULT NULL,
  `ROOM` varchar(120) DEFAULT NULL COMMENT '室',
  `SCOL1` varchar(300) DEFAULT NULL COMMENT '冗余字段1',
  `SCOL2` varchar(300) DEFAULT NULL COMMENT '冗余字段2',
  `SCOL3` varchar(300) DEFAULT NULL COMMENT '冗余字段3',
  `SCOL4` datetime DEFAULT NULL COMMENT '冗余字段4',
  `SCONTACT` varchar(300) DEFAULT NULL COMMENT '联系方式',
  `SEAT` varchar(120) DEFAULT NULL COMMENT '楼座',
  `SECURITY_LEVEL` varchar(3) DEFAULT NULL COMMENT '信息级别',
  `SERVICE_FOR` varchar(150) DEFAULT NULL COMMENT '服务处所',
  `SMEMO` varchar(300) DEFAULT NULL COMMENT '备注',
  `SOTHER_ADDR` varchar(300) DEFAULT NULL COMMENT '其他地址',
  `SXZJD` varchar(120) DEFAULT NULL COMMENT '乡镇街道',
  `SXZJD_ID` varchar(9) DEFAULT NULL COMMENT '乡镇街道编号',
  `SYSTEMID` varchar(100) NOT NULL COMMENT '系统主键',
  `TEAMID` varchar(45) DEFAULT NULL COMMENT '组号',
  `TOPONYM` varchar(120) DEFAULT NULL COMMENT '地名',
  `TOPONYM_ID` varchar(21) DEFAULT NULL COMMENT '地名编号',
  `TO_ADDR` varchar(300) DEFAULT NULL COMMENT '迁往地',
  `TO_COUNTRY_ID` varchar(6) DEFAULT NULL COMMENT '迁往地（国家地区）',
  `TO_COUNTRY_ID_ZW` varchar(255) DEFAULT NULL COMMENT '迁往地（国家地区）',
  `TO_COUNTRY_ID_GABZ` varchar(3) DEFAULT NULL COMMENT '迁往地（国家地区）_公安标准',
  `TO_ORG_ID` varchar(12) DEFAULT NULL COMMENT '迁往地（组织机构）',
  `TO_ORG_ID_ZW` varchar(255) DEFAULT NULL COMMENT '迁往地（组织机构）',
  `TO_ORG_ID_GABZ` varchar(12) DEFAULT NULL COMMENT '迁往地（组织机构）_公安标准',
  `TO_PLACE_ID` varchar(12) DEFAULT NULL COMMENT '迁往地（居村委）',
  `TO_PLACE_ID_ZW` varchar(255) DEFAULT NULL,
  `TO_REGION_ID` varchar(10) DEFAULT NULL COMMENT '迁往地（省市县区）',
  `TO_REGION_ID_ZW` varchar(255) DEFAULT NULL,
  `TO_REGION_ID_GABZ` varchar(6) DEFAULT NULL COMMENT '迁往地（省市县区）_公安标准',
  `USED_NAME` varchar(45) DEFAULT NULL COMMENT '曾用名',
  `WARDSHIP_1` varchar(75) DEFAULT NULL COMMENT '与监护人1关系',
  `WARDSHIP_1_ZW` varchar(255) DEFAULT NULL COMMENT '与监护人1关系',
  `WARDSHIP_1_CODE` varchar(6) DEFAULT NULL COMMENT '与监护人1关系',
  `WARDSHIP_2` varchar(75) DEFAULT NULL COMMENT '与监护人2关系',
  `WARDSHIP_2_ZW` varchar(255) DEFAULT NULL COMMENT '与监护人2关系',
  `WARDSHIP_2_CODE` varchar(6) DEFAULT NULL COMMENT '与监护人2关系',
  `WHEN_IN` date DEFAULT NULL COMMENT '迁入时间',
  `WHEN_IN_LOGGED` date DEFAULT NULL COMMENT '办理迁入时间',
  `WHEN_LOGGED` date DEFAULT NULL COMMENT '与户主关系创建时间',
  `WHEN_OUT` date DEFAULT NULL COMMENT '迁出时间',
  `WHEN_OUT_LOGGED` date DEFAULT NULL COMMENT '办理时间',
  `WHEN_PCARD_ISSUED` date DEFAULT NULL COMMENT '持证件签发时间',
  `WHO_IN_LOGGED` varchar(21) DEFAULT NULL COMMENT '办理人',
  `WHO_IN_LOGGED_NAME` varchar(45) DEFAULT NULL COMMENT '办理人姓名',
  `WHO_IN_UNIT` varchar(12) DEFAULT NULL COMMENT '办理单位',
  `WHO_IN_UNIT_ZW` varchar(255) DEFAULT NULL,
  `WHO_IN_UNIT_GABZ` varchar(12) DEFAULT NULL COMMENT '办理单位_公安标准',
  `WHO_IN_UNIT_NAME` varchar(120) DEFAULT NULL COMMENT '办理单位名称',
  `WHO_OUT_LOGGED` varchar(21) DEFAULT NULL COMMENT '办理人',
  `WHO_OUT_LOGGED_NAME` varchar(45) DEFAULT NULL COMMENT '办理人姓名',
  `WHO_OUT_UNIT` varchar(12) DEFAULT NULL COMMENT '办理单位',
  `WHO_OUT_UNIT_ZW` varchar(255) DEFAULT NULL,
  `WHO_OUT_UNIT_GABZ` varchar(12) DEFAULT NULL COMMENT '办理单位_公安标准',
  `WHO_OUT_UNIT_NAME` varchar(120) DEFAULT NULL COMMENT '办理单位名称',
  `YXTBH` varchar(21) DEFAULT NULL COMMENT '户籍编号',
  `ZXBZ` varchar(1) DEFAULT NULL COMMENT '注销标志（0：有效1无效）',
  `ZXLB` varchar(1) DEFAULT NULL COMMENT '注销类别',
  `ZXLB_CODE` varchar(1) DEFAULT NULL COMMENT '注销类别',
  `ZYK_SSXTMC` varchar(18) DEFAULT NULL COMMENT '所属系统名称',
  `ZZZK` varchar(3) DEFAULT NULL COMMENT '在住状况',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
