/*
Navicat MySQL Data Transfer

Source Server         : jwzh
Source Server Version : 50538
Source Host           : localhost:3306
Source Database       : source_jg

Target Server Type    : MYSQL
Target Server Version : 50538
File Encoding         : 65001

Date: 2017-03-24 16:38:17
*/

SET FOREIGN_KEY_CHECKS=0;
DROP Database IF EXISTS `source_jg`;
CREATE Database `source_jg`;
use source_jg;
-- ----------------------------
-- Table structure for code_clyt
-- ----------------------------
DROP TABLE IF EXISTS `code_clyt`;
CREATE TABLE `code_clyt` (
  `hck_gxsj` datetime DEFAULT NULL,
  `bz` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `code` varchar(255) NOT NULL,
  `hck_rksj` datetime DEFAULT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for code_csys
-- ----------------------------
DROP TABLE IF EXISTS `code_csys`;
CREATE TABLE `code_csys` (
  `code` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `bz` varchar(255) DEFAULT NULL,
  `hck_gxsj` datetime DEFAULT NULL,
  `hck_rksj` datetime DEFAULT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_jg_jdcxxb
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_jg_jdcxxb`;
CREATE TABLE `t_bz_jg_jdcxxb` (
  `SYSTEMID` varchar(50) NOT NULL COMMENT '系统主键',
  `BDJCS` int(11) DEFAULT NULL COMMENT '补/换领证书次数',
  `BPCS` int(11) DEFAULT NULL COMMENT '补领号牌次数',
  `BXZZRQ` date DEFAULT NULL COMMENT '保险终止日期',
  `BZ` varchar(192) DEFAULT NULL COMMENT '备注',
  `BZCS` int(11) DEFAULT NULL COMMENT '补领行驶证次数',
  `CCDJRQ` date DEFAULT NULL COMMENT '初次登记日期',
  `CCRQ` date DEFAULT NULL COMMENT '出厂日期',
  `CLLX` varchar(3) DEFAULT NULL COMMENT '车辆类型',
  `CLLX_GABZ` varchar(3) DEFAULT NULL COMMENT '车辆类型_公安标准',
  `CLLY` varchar(1) DEFAULT NULL COMMENT '车辆来源:1注册2转入3过户',
  `CLPP1` varchar(48) DEFAULT NULL COMMENT '中文品牌',
  `CLPP2` varchar(48) DEFAULT NULL COMMENT '英文品牌',
  `CLSBDH` varchar(38) DEFAULT NULL COMMENT '车辆识别代号',
  `CLXH` varchar(48) DEFAULT NULL COMMENT '车辆型号',
  `CLYT` varchar(2) DEFAULT NULL COMMENT '车辆用途',
  `CSYS` varchar(8) DEFAULT NULL COMMENT '车身颜色',
  `CSYS_GABZ` varchar(1) DEFAULT NULL COMMENT '车身颜色_公安标准',
  `CWKC` int(11) DEFAULT NULL COMMENT '车外廓长',
  `CWKG` int(11) DEFAULT NULL COMMENT '车外廓高',
  `CWKK` int(11) DEFAULT NULL COMMENT '车外廓宽',
  `CYRY` varchar(45) DEFAULT NULL COMMENT '查验人员',
  `DABH` varchar(18) DEFAULT NULL COMMENT '档案编号',
  `DJRQ` date DEFAULT NULL COMMENT '最近定检日期',
  `DJZSBH` varchar(23) DEFAULT NULL COMMENT '登记证书编号',
  `DPHGZBH` varchar(30) DEFAULT NULL COMMENT '底盘合格证编号',
  `DWBH` varchar(21) DEFAULT NULL COMMENT '单位编号',
  `DWBH_GABZ` varchar(12) DEFAULT NULL COMMENT '单位编号_公安标准',
  `DYBJ` varchar(1) DEFAULT NULL COMMENT '是否抵押:0-未抵押，1-已抵押',
  `DZYX` varchar(48) DEFAULT NULL COMMENT '电子邮箱',
  `FDJGS` int(11) DEFAULT NULL COMMENT '发动机缸数',
  `FDJH` varchar(45) DEFAULT NULL COMMENT '发动机号',
  `FDJRQ` date DEFAULT NULL COMMENT '发登记证书日期',
  `FDJXH` varchar(96) DEFAULT NULL COMMENT '发动机型号',
  `FHGZRQ` date DEFAULT NULL COMMENT '发合格证日期',
  `FPRQ` date DEFAULT NULL COMMENT '发牌日期',
  `FZJG` varchar(15) DEFAULT NULL COMMENT '发证机关',
  `FZRQ` date DEFAULT NULL COMMENT '发行驶证日期',
  `GBTHPS` int(11) DEFAULT NULL COMMENT '钢板弹簧片数',
  `GCJK` varchar(1) DEFAULT NULL COMMENT '国产/进口',
  `GL` decimal(5,1) DEFAULT NULL COMMENT '功率',
  `GLBM` varchar(18) DEFAULT NULL COMMENT '管理部门',
  `GLBM_GABZ` varchar(12) DEFAULT NULL COMMENT '管理部门_公安标准',
  `GXRQ` date DEFAULT NULL COMMENT '更新日期',
  `HBDBQK` varchar(192) DEFAULT NULL COMMENT '环保达标情况',
  `HCK_GXSJ` datetime DEFAULT NULL COMMENT '更新时间',
  `HCK_RKSJ` datetime DEFAULT NULL COMMENT '入库时间',
  `HDFS` varchar(1) DEFAULT NULL COMMENT '获得方式',
  `HDZK` int(11) DEFAULT NULL COMMENT '核定载客',
  `HDZZL` int(11) DEFAULT NULL COMMENT '核定载质量',
  `HGZBH` varchar(30) DEFAULT NULL COMMENT '合格证编号',
  `HLJ` int(11) DEFAULT NULL COMMENT '后轮距',
  `HMBH` varchar(23) DEFAULT NULL COMMENT '后膜编号',
  `YXTBH_HPHM` varchar(23) DEFAULT NULL COMMENT '号牌号码',
  `HPZK` int(11) DEFAULT NULL COMMENT '驾驶室后排载客人数',
  `YXTBH_HPZL` varchar(2) DEFAULT NULL COMMENT '号牌种类',
  `YXTBH_HPZL_GABZ` varchar(2) DEFAULT NULL COMMENT '号牌种类_公安标准',
  `HXNBCD` int(11) DEFAULT NULL COMMENT '货箱内部长度',
  `HXNBGD` int(11) DEFAULT NULL COMMENT '货箱内部高度',
  `HXNBKD` int(11) DEFAULT NULL COMMENT '货箱内部宽度',
  `JBR` varchar(45) DEFAULT NULL COMMENT '经办人',
  `JKPZ` varchar(1) DEFAULT NULL COMMENT '进口凭证',
  `JKPZHM` varchar(30) DEFAULT NULL COMMENT '进口凭证编号',
  `JYHGBZBH` varchar(30) DEFAULT NULL COMMENT '检验合格标志',
  `JYW` varchar(384) DEFAULT NULL COMMENT '校验位',
  `LLPZ1` varchar(1) DEFAULT NULL COMMENT '来历凭证1',
  `LLPZ2` varchar(1) DEFAULT NULL COMMENT '来历凭证2',
  `LSH` varchar(20) DEFAULT NULL COMMENT '注册流水号',
  `LTGG` varchar(96) DEFAULT NULL COMMENT '轮胎规格',
  `LTS` int(11) DEFAULT NULL COMMENT '轮胎数',
  `LXDH` varchar(30) DEFAULT NULL COMMENT '联系电话',
  `NCDQSY` varchar(1) DEFAULT NULL COMMENT '是否为农村地区使用 1-是；2-否',
  `NSZM` varchar(1) DEFAULT NULL COMMENT '纳税证明',
  `NSZMBH` varchar(30) DEFAULT NULL COMMENT '纳税证明编号',
  `PL` int(11) DEFAULT NULL COMMENT '排量',
  `PZBH1` varchar(30) DEFAULT NULL COMMENT '凭证编号1',
  `PZBH2` varchar(255) DEFAULT NULL COMMENT '凭证编号2',
  `QLJ` int(11) DEFAULT NULL COMMENT '前轮距',
  `QMBH` varchar(23) DEFAULT NULL COMMENT '前膜编号',
  `QPZK` int(11) DEFAULT NULL COMMENT '驾驶室前排载客人数',
  `QZBFQZ` date DEFAULT NULL COMMENT '强制报废期止',
  `RLZL` varchar(5) DEFAULT NULL COMMENT '燃料种类',
  `SFYZHGN` varchar(1) DEFAULT NULL COMMENT '专项作业车是否有载货功能 1-是；2-否',
  `SFZMHM` varchar(27) DEFAULT NULL COMMENT '身份证明号码',
  `SFZMMC` varchar(1) DEFAULT NULL COMMENT '身份证明名称',
  `SJHM` varchar(30) DEFAULT NULL COMMENT '手机号码',
  `SQDM` varchar(12) DEFAULT NULL COMMENT '社区代码',
  `SYQ` varchar(1) DEFAULT NULL COMMENT '所有权',
  `SYQSRQ` date DEFAULT NULL COMMENT '使用起始日期',
  `SYR` varchar(192) DEFAULT NULL COMMENT '机动车所有人',
  `SYXZ` varchar(1) DEFAULT NULL COMMENT '使用性质',
  `WXMBC` varchar(1) DEFAULT NULL COMMENT '是否为微型面包车 1-是；2-否',
  `XGZL` varchar(384) DEFAULT NULL COMMENT '相关资料',
  `XH` varchar(14) DEFAULT NULL COMMENT '机动车序号',
  `XSDW` varchar(96) DEFAULT NULL COMMENT '销售单位',
  `XSJG` int(11) DEFAULT NULL COMMENT '销售价格',
  `XSRQ` date DEFAULT NULL COMMENT '销售日期',
  `XSZBH` varchar(30) DEFAULT NULL COMMENT '行驶证证芯编号',
  `XZQH` varchar(15) DEFAULT NULL COMMENT '管理辖区',
  `XZQH_GABZ` varchar(6) DEFAULT NULL COMMENT '管理辖区_公安标准',
  `YQJYQZ2` date DEFAULT NULL COMMENT '逾期2个检验周期期止',
  `YQJYQZBFQZ` date DEFAULT NULL COMMENT '逾期检验强制报废期止',
  `YTSX` varchar(1) DEFAULT NULL COMMENT '用途属性',
  `YXH` varchar(21) DEFAULT NULL COMMENT '原机动车序号',
  `YXQZ` date DEFAULT NULL COMMENT '检验有效期止',
  `YZBM1` varchar(9) DEFAULT NULL COMMENT '住所邮政编码',
  `YZBM2` varchar(9) DEFAULT NULL COMMENT '暂住邮政编码',
  `ZBZL` int(11) DEFAULT NULL COMMENT '整备质量',
  `ZDJZSHS` int(11) DEFAULT NULL COMMENT '制登记证书行数',
  `ZDYZT` varchar(15) DEFAULT NULL COMMENT '自定义状态',
  `ZJ` int(11) DEFAULT NULL COMMENT '轴距',
  `ZQYZL` int(11) DEFAULT NULL COMMENT '准牵引总质量',
  `ZS` int(11) DEFAULT NULL COMMENT '轴数',
  `ZSXXDZ` varchar(192) DEFAULT NULL COMMENT '住所详细地址',
  `ZSXZQH` varchar(15) DEFAULT NULL COMMENT '住所行政区划',
  `ZSXZQH_GABZ` varchar(6) DEFAULT NULL COMMENT '住所行政区划_公安标准',
  `ZT` varchar(9) DEFAULT NULL COMMENT '机动车状态',
  `ZXXS` varchar(1) DEFAULT NULL COMMENT '转向形式',
  `ZZCMC` varchar(96) DEFAULT NULL COMMENT '制造厂名称',
  `ZZG` varchar(3) DEFAULT NULL COMMENT '制造国',
  `ZZG_GABZ` varchar(3) DEFAULT NULL COMMENT '制造国_公安标准',
  `ZZJGLX` varchar(3) DEFAULT NULL COMMENT '组织机构类型  CODE=0021',
  `ZZL` int(11) DEFAULT NULL COMMENT '总质量',
  `ZZXXDZ` varchar(192) DEFAULT NULL COMMENT '暂住详细地址',
  `ZZXZQH` varchar(15) DEFAULT NULL COMMENT '暂住行政区划',
  `ZZXZQH_GABZ` varchar(6) DEFAULT NULL COMMENT '暂住行政区划_公安标准',
  `ZZZ` varchar(27) DEFAULT NULL COMMENT '暂住居住证明',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  `CLLY_GABZ` varchar(1) DEFAULT NULL COMMENT '车辆来源:1注册2转入3过户_公安标准',
  `CLYT_GABZ` varchar(2) DEFAULT NULL COMMENT '车辆用途_公安标准',
  `DYBJ_GABZ` varchar(1) DEFAULT NULL COMMENT '是否抵押:0-未抵押，1-已抵押_公安标准',
  `FZJG_GABZ` varchar(15) DEFAULT NULL COMMENT '发证机关_公安标准',
  `GCJK_GABZ` varchar(1) DEFAULT NULL COMMENT '国产/进口_公安标准',
  `HDFS_GABZ` varchar(1) DEFAULT NULL COMMENT '获得方式_公安标准',
  `JKPZ_GABZ` varchar(1) DEFAULT NULL COMMENT '进口凭证_公安标准',
  `LLPZ1_GABZ` varchar(1) DEFAULT NULL COMMENT '来历凭证1_公安标准',
  `LLPZ2_GABZ` varchar(1) DEFAULT NULL COMMENT '来历凭证2_公安标准',
  `NSZM_GABZ` varchar(1) DEFAULT NULL COMMENT '纳税证明_公安标准',
  `RLZL_GABZ` varchar(5) DEFAULT NULL COMMENT '燃料种类_公安标准',
  `SFZMMC_GABZ` varchar(3) DEFAULT NULL COMMENT '身份证明名称_公安标准',
  `SYQ_GABZ` varchar(1) DEFAULT NULL COMMENT '所有权_公安标准',
  `SYXZ_GABZ` varchar(1) DEFAULT NULL COMMENT '使用性质_公安标准',
  `XGZL_GABZ` varchar(384) DEFAULT NULL COMMENT '相关资料_公安标准',
  `YTSX_GABZ` varchar(1) DEFAULT NULL COMMENT '用途属性_公安标准',
  `ZT_GABZ` varchar(1) DEFAULT NULL COMMENT '机动车状态_公安标准',
  `ZXXS_GABZ` varchar(1) DEFAULT NULL COMMENT '转向形式_公安标准',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for t_bz_jg_jsrjzxx
-- ----------------------------
DROP TABLE IF EXISTS `t_bz_jg_jsrjzxx`;
CREATE TABLE `t_bz_jg_jsrjzxx` (
  `SYSTEMID` varchar(50) NOT NULL COMMENT '系统主键',
  `BZ` varchar(384) DEFAULT NULL COMMENT '备注',
  `BZCS` int(11) DEFAULT NULL COMMENT '补证次数',
  `CCFZJG` varchar(15) DEFAULT NULL COMMENT '初次发证机关',
  `CCLZRQ` date DEFAULT NULL COMMENT '初次领证日期',
  `CFRQ` date DEFAULT NULL COMMENT '超分日期',
  `CSRQ` date DEFAULT NULL COMMENT '出生日期',
  `DABH` varchar(12) DEFAULT NULL COMMENT '档案编号',
  `DABH_GABZ` varchar(12) DEFAULT NULL COMMENT '档案编号_公安标准',
  `DJZSXXDZ` varchar(192) DEFAULT NULL COMMENT '登记住所详细地址',
  `DJZSXZQH` varchar(15) DEFAULT NULL COMMENT '登记住所行政区划',
  `DJZSXZQH_GABZ` varchar(6) DEFAULT NULL COMMENT '登记住所行政区划_公安标准',
  `DWBH` varchar(21) DEFAULT NULL COMMENT '单位编号?',
  `DZYX` varchar(45) DEFAULT NULL COMMENT '电子邮箱',
  `FZJG` varchar(15) DEFAULT NULL COMMENT '发证机关',
  `FZRQ` date DEFAULT NULL COMMENT '发证日期',
  `GJ` varchar(3) DEFAULT NULL COMMENT '国籍',
  `GJ_GABZ` varchar(3) DEFAULT NULL COMMENT '国籍_公安标准',
  `GLBM` varchar(18) DEFAULT NULL COMMENT '管理部门',
  `GLBM_GABZ` varchar(12) DEFAULT NULL COMMENT '管理部门_公安标准',
  `GXSJ` datetime DEFAULT NULL COMMENT '更新时间',
  `HCK_GXSJ` datetime DEFAULT NULL COMMENT '更新时间',
  `HCK_RKSJ` datetime DEFAULT NULL COMMENT '入库时间',
  `HMCD` varchar(1) DEFAULT NULL COMMENT '号码长度',
  `JBR` varchar(45) DEFAULT NULL COMMENT '经办人',
  `JLY` varchar(45) DEFAULT NULL COMMENT '教练员',
  `JXMC` varchar(96) DEFAULT NULL COMMENT '驾校名称',
  `JYW` varchar(384) DEFAULT NULL COMMENT '校验位',
  `JZQX` varchar(1) DEFAULT NULL COMMENT '驾证期限',
  `LJJF` int(11) DEFAULT NULL COMMENT '累积记分',
  `LSH` varchar(20) DEFAULT NULL COMMENT '流水号',
  `LXDH` varchar(30) DEFAULT NULL COMMENT '联系电话',
  `LXZSXXDZ` varchar(192) DEFAULT NULL COMMENT '联系住所详细地址',
  `LXZSXZQH` varchar(15) DEFAULT NULL COMMENT '联系住所行政区划',
  `LXZSXZQH_GABZ` varchar(6) DEFAULT NULL COMMENT '联系住所行政区划_公安标准',
  `LXZSYZBM` varchar(9) DEFAULT NULL COMMENT '联系住所邮政编码',
  `LY` varchar(1) DEFAULT NULL COMMENT '驾驶人来源',
  `QFRQ` date DEFAULT NULL COMMENT '下一清分日期',
  `RYZT` varchar(1) DEFAULT NULL COMMENT '人员状态。0：正常；1：有吸毒记录',
  `SFBD` varchar(1) DEFAULT NULL COMMENT '是否本地',
  `SFZMHM` varchar(27) DEFAULT NULL COMMENT '身份证明号码',
  `SFZMMC` varchar(1) DEFAULT NULL COMMENT '身份证明名称',
  `SJHM` varchar(30) DEFAULT NULL COMMENT '手机号码',
  `SQDM` varchar(18) DEFAULT NULL COMMENT '社区代码',
  `SXBJ` varchar(1) DEFAULT NULL COMMENT '实习标记1是2否',
  `SXQKSBJ` varchar(1) DEFAULT NULL COMMENT '实习期考试标记0未参加1参加',
  `SYRQ` date DEFAULT NULL COMMENT '下一审验日期',
  `SYYXQZ` date DEFAULT NULL COMMENT '审验有效期止',
  `XB` varchar(1) DEFAULT NULL COMMENT '性别1男2女',
  `XB_GABZ` varchar(1) DEFAULT NULL COMMENT '性别1男2女_公安标准',
  `XCZG` varchar(1) DEFAULT NULL COMMENT '校车驾驶资格1有0无',
  `XCZJCX` varchar(23) DEFAULT NULL COMMENT '校车资格准驾车型',
  `XGZL` varchar(23) DEFAULT NULL COMMENT '相关资料',
  `YXTBH` varchar(15) DEFAULT NULL COMMENT '序号',
  `XM` varchar(45) DEFAULT NULL COMMENT '姓名',
  `XXTZRQ` date DEFAULT NULL COMMENT '学习通知日期',
  `XZCRQ` date DEFAULT NULL COMMENT '需转出日期',
  `XZQH` varchar(15) DEFAULT NULL COMMENT '行政区划',
  `XZQH_GABZ` varchar(6) DEFAULT NULL COMMENT '行政区划_公安标准',
  `XZQJ` varchar(15) DEFAULT NULL COMMENT '乡镇区局',
  `YDABH` varchar(12) DEFAULT NULL COMMENT '原档案编号',
  `YXQS` date DEFAULT NULL COMMENT '有效期始',
  `YXQZ` date DEFAULT NULL COMMENT '有效期止',
  `YZJCX` varchar(45) DEFAULT NULL COMMENT '原准驾车型',
  `ZJCX` varchar(23) DEFAULT NULL COMMENT '准驾车型',
  `ZT` varchar(9) DEFAULT NULL COMMENT '驾驶证状态',
  `ZXBH` varchar(13) DEFAULT NULL COMMENT '证芯编号',
  `ZZFZJG` varchar(45) DEFAULT NULL COMMENT '暂住发证机关',
  `ZZFZRQ` date DEFAULT NULL COMMENT '暂住发证日期',
  `ZZZM` varchar(27) DEFAULT NULL COMMENT '暂住证明',
  `BZK_ZZJG` varchar(12) DEFAULT NULL COMMENT '标准库组织机构',
  `BZK_RKSJ` datetime DEFAULT NULL COMMENT '标准库入库时间',
  `BZK_GXSJ` datetime DEFAULT NULL COMMENT '标准库更新时间',
  `ZYK_SSXTMC` varchar(100) DEFAULT NULL COMMENT '所属系统名称',
  `BZK_SCBZ` varchar(1) DEFAULT NULL COMMENT '标准库删除标识',
  PRIMARY KEY (`SYSTEMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
